import type { ProficiencyLevel } from '@/types';
import type { PresetScenarioId, RoleplayScenario } from './types';

/**
 * Every preset belongs to exactly one CEFR level — five scenarios per level,
 * so a learner never sees the same scene twice as they progress.
 */
export const ROLEPLAY_SCENARIOS: RoleplayScenario[] = [
  // ─── A1 · sobrevivência ─────────────────────────────────────────────────────
  {
    id: 'a1-cafe',
    titlePt: 'Pedido no café',
    descriptionPt: 'Peça uma bebida e pergunte o preço.',
    characterName: 'Alex',
    characterRolePt: 'barista simpático',
    userRolePt: 'cliente',
    objectivePt: 'Pedir uma bebida e confirmar o preço',
    goalsPt: ['Cumprimentar o barista', 'Pedir uma bebida', 'Perguntar quanto custa'],
    settingPt: 'um café pequeno de bairro',
    openingHint: 'Greet the customer warmly and ask what they would like to drink.',
    level: 'A1',
  },
  {
    id: 'a1-apresentacao',
    titlePt: 'Novo colega',
    descriptionPt: 'Apresente-se no primeiro dia de curso.',
    characterName: 'Emma',
    characterRolePt: 'colega de turma curioso(a)',
    userRolePt: 'estudante novo(a)',
    objectivePt: 'Dizer seu nome, de onde você é e o que faz',
    goalsPt: ['Dizer seu nome', 'Dizer de onde você é', 'Perguntar o nome da outra pessoa'],
    settingPt: 'o primeiro dia de um curso de idiomas',
    openingHint: 'Say hello, introduce yourself by name, and ask for theirs.',
    level: 'A1',
  },
  {
    id: 'a1-passagem',
    titlePt: 'Comprar passagem',
    descriptionPt: 'Compre um bilhete de trem para hoje.',
    characterName: 'Luc',
    characterRolePt: 'atendente da bilheteria',
    userRolePt: 'passageiro(a)',
    objectivePt: 'Comprar um bilhete e confirmar o horário',
    goalsPt: ['Dizer para onde você vai', 'Pedir um bilhete', 'Confirmar o horário de partida'],
    settingPt: 'a bilheteria de uma estação de trem',
    openingHint: 'Ask where the passenger would like to travel today.',
    level: 'A1',
  },
  {
    id: 'a1-feira',
    titlePt: 'Na feira',
    descriptionPt: 'Pergunte preços e compre frutas.',
    characterName: 'Nina',
    characterRolePt: 'feirante animada',
    userRolePt: 'cliente',
    objectivePt: 'Perguntar preços e comprar duas frutas',
    goalsPt: ['Perguntar o preço', 'Pedir uma quantidade', 'Agradecer e se despedir'],
    settingPt: 'uma feira de rua no sábado de manhã',
    openingHint: "Call the customer over and offer today's fresh fruit.",
    level: 'A1',
  },
  {
    id: 'a1-farmacia',
    titlePt: 'Na farmácia',
    descriptionPt: 'Peça um remédio e confirme o horário.',
    characterName: 'Paul',
    characterRolePt: 'farmacêutico(a)',
    userRolePt: 'cliente',
    objectivePt: 'Pedir um remédio e entender as instruções',
    goalsPt: [
      'Dizer o que você precisa',
      'Perguntar a dose ou o horário',
      'Confirmar o preço',
    ],
    settingPt: 'uma farmácia de bairro no fim da tarde',
    openingHint: 'Greet the customer and ask how you can help.',
    level: 'A1',
  },

  // ─── A2 · rotina ────────────────────────────────────────────────────────────
  {
    id: 'a2-hotel',
    titlePt: 'Check-in no hotel',
    descriptionPt: 'Faça check-in e tire dúvidas do quarto.',
    characterName: 'Sam',
    characterRolePt: 'recepcionista do hotel',
    userRolePt: 'hóspede',
    objectivePt: 'Fazer check-in e perguntar sobre o café da manhã',
    goalsPt: [
      'Dar seu nome e a reserva',
      'Perguntar o horário do café da manhã',
      'Perguntar a senha do wi-fi',
    ],
    settingPt: 'a recepção de um hotel pequeno à noite',
    openingHint: 'Welcome the guest and offer to start the check-in.',
    level: 'A2',
  },
  {
    id: 'a2-consulta',
    titlePt: 'Consulta rápida',
    descriptionPt: 'Descreva sintomas e entenda a orientação.',
    characterName: 'Dra. Lee',
    characterRolePt: 'médica de família paciente',
    userRolePt: 'paciente',
    objectivePt: 'Descrever sintomas e entender a orientação',
    goalsPt: [
      'Descrever dois sintomas',
      'Dizer desde quando começou',
      'Repetir a orientação recebida',
    ],
    settingPt: 'um consultório simples de bairro',
    openingHint: 'Ask the patient what brings them in today.',
    level: 'A2',
  },
  {
    id: 'a2-combinar',
    titlePt: 'Combinar um plano',
    descriptionPt: 'Marque dia, hora e lugar com um amigo.',
    characterName: 'Mia',
    characterRolePt: 'amiga próxima',
    userRolePt: 'amigo(a)',
    objectivePt: 'Combinar dia, hora e lugar de um encontro',
    goalsPt: ['Sugerir uma atividade', 'Combinar dia e hora', 'Definir o ponto de encontro'],
    settingPt: 'uma ligação no fim da tarde',
    openingHint: 'Greet your friend warmly and suggest doing something this week.',
    level: 'A2',
  },
  {
    id: 'a2-troca',
    titlePt: 'Trocar uma compra',
    descriptionPt: 'Explique o problema e consiga a troca.',
    characterName: 'Théo',
    characterRolePt: 'vendedor(a) do balcão de trocas',
    userRolePt: 'cliente',
    objectivePt: 'Explicar o problema e conseguir a troca',
    goalsPt: [
      'Explicar o que está errado',
      'Pedir a troca ou o reembolso',
      'Confirmar o que vai acontecer',
    ],
    settingPt: 'o balcão de trocas de uma loja de roupas',
    openingHint: 'Ask how you can help them at the returns desk.',
    level: 'A2',
  },
  {
    id: 'a2-entrega',
    titlePt: 'Receber uma entrega',
    descriptionPt: 'Confirme o endereço e assine a entrega.',
    characterName: 'Léa',
    characterRolePt: 'entregador(a)',
    userRolePt: 'morador(a)',
    objectivePt: 'Confirmar o pedido e receber a entrega',
    goalsPt: [
      'Confirmar seu nome e endereço',
      'Perguntar se precisa assinar',
      'Agradecer e se despedir',
    ],
    settingPt: 'a porta do seu apartamento',
    openingHint: 'Ring the doorbell and say you have a delivery for them.',
    level: 'A2',
  },

  // ─── B1 · resolver problemas ────────────────────────────────────────────────
  {
    id: 'b1-voo-cancelado',
    titlePt: 'Voo cancelado',
    descriptionPt: 'Remarque o voo e resolva a bagagem.',
    characterName: 'Clara',
    characterRolePt: 'agente da companhia aérea',
    userRolePt: 'passageiro(a)',
    objectivePt: 'Remarcar o voo e resolver a bagagem',
    goalsPt: [
      'Explicar sua situação',
      'Pedir uma alternativa para hoje',
      'Confirmar bagagem e novo horário',
    ],
    settingPt: 'o balcão da companhia aérea num aeroporto cheio',
    openingHint: 'Apologise for the cancellation and ask for their booking details.',
    level: 'B1',
  },
  {
    id: 'b1-atraso',
    titlePt: 'Explicar um atraso',
    descriptionPt: 'Assuma o atraso e proponha novo prazo.',
    characterName: 'Marco',
    characterRolePt: 'chefe direto',
    userRolePt: 'membro da equipe',
    objectivePt: 'Explicar o atraso e propor um novo prazo',
    goalsPt: ['Assumir o atraso sem rodeios', 'Explicar o motivo', 'Propor um prazo realista'],
    settingPt: 'uma conversa rápida na mesa do chefe',
    openingHint: 'Ask calmly why the work is late.',
    level: 'B1',
  },
  {
    id: 'b1-triagem',
    titlePt: 'Triagem por telefone',
    descriptionPt: 'Resuma sua experiência e pergunte da vaga.',
    characterName: 'Priya',
    characterRolePt: 'recrutadora',
    userRolePt: 'candidato(a)',
    objectivePt: 'Apresentar sua experiência e perguntar sobre a vaga',
    goalsPt: [
      'Resumir sua experiência em poucas frases',
      'Dizer por que quer a vaga',
      'Fazer uma pergunta sobre o trabalho',
    ],
    settingPt: 'uma ligação de triagem de dez minutos',
    openingHint: 'Introduce yourself as the recruiter and ask them to walk you through their background.',
    level: 'B1',
  },
  {
    id: 'b1-reclamacao',
    titlePt: 'Reclamar de um serviço',
    descriptionPt: 'Reclame com educação e peça solução.',
    characterName: 'Hugo',
    characterRolePt: 'gerente do restaurante',
    userRolePt: 'cliente',
    objectivePt: 'Reclamar com educação e pedir uma solução',
    goalsPt: [
      'Descrever o problema com fatos',
      'Dizer como isso te afetou',
      'Pedir uma solução concreta',
    ],
    settingPt: 'um restaurante no fim do jantar',
    openingHint: 'Notice the customer wants to talk and ask if everything was alright.',
    level: 'B1',
  },
  {
    id: 'b1-vizinho',
    titlePt: 'Vizinho barulhento',
    descriptionPt: 'Peça silêncio com educação e combine um horário.',
    characterName: 'Olivier',
    characterRolePt: 'vizinho barulhento',
    userRolePt: 'vizinho(a)',
    objectivePt: 'Pedir silêncio com educação e combinar um horário',
    goalsPt: [
      'Explicar o problema sem acusar',
      'Propor um horário mais calmo',
      'Fechar um acordo amigável',
    ],
    settingPt: 'o corredor do prédio à noite',
    openingHint: 'Open the door a bit surprised and ask what is going on.',
    level: 'B1',
  },

  // ─── B2 · negociar e argumentar ─────────────────────────────────────────────
  {
    id: 'b2-salario',
    titlePt: 'Negociar salário',
    descriptionPt: 'Justifique sua faixa e feche um acordo.',
    characterName: 'Renata',
    characterRolePt: 'gerente de contratação',
    userRolePt: 'candidato(a) finalista',
    objectivePt: 'Justificar sua faixa salarial e chegar a um acordo',
    goalsPt: [
      'Dizer sua faixa com justificativa',
      'Responder a uma objeção',
      'Propor um próximo passo',
    ],
    settingPt: 'a última etapa de um processo seletivo',
    openingHint: 'Say you are impressed and ask about their salary expectations.',
    level: 'B2',
  },
  {
    id: 'b2-conflito',
    titlePt: 'Conflito na equipe',
    descriptionPt: 'Discorde com respeito e combine um acordo.',
    characterName: 'Karim',
    characterRolePt: 'colega irritado',
    userRolePt: 'colega de equipe',
    objectivePt: 'Ouvir, discordar com respeito e combinar um acordo',
    goalsPt: [
      'Reconhecer o ponto do colega',
      'Apresentar sua visão sem atacar',
      'Fechar um acordo prático',
    ],
    settingPt: 'uma sala de reunião depois de um projeto tenso',
    openingHint: 'Say directly but politely that you were unhappy with how the project went.',
    level: 'B2',
  },
  {
    id: 'b2-turismo',
    titlePt: 'Turismo demais?',
    descriptionPt: 'Defenda sua opinião com exemplos.',
    characterName: 'Iris',
    characterRolePt: 'jornalista local',
    userRolePt: 'entrevistado(a)',
    objectivePt: 'Defender sua opinião com exemplos concretos',
    goalsPt: ['Dar sua opinião com clareza', 'Sustentar com um exemplo', 'Reconhecer o outro lado'],
    settingPt: 'uma entrevista de rua sobre turismo na cidade',
    openingHint: 'Ask whether mass tourism helps or hurts the city.',
    level: 'B2',
  },
  {
    id: 'b2-cliente',
    titlePt: 'Convencer um cliente',
    descriptionPt: 'Entenda a objeção e proponha um teste.',
    characterName: 'Daniel',
    characterRolePt: 'cliente cético',
    userRolePt: 'consultor(a)',
    objectivePt: 'Entender a objeção e propor um próximo passo',
    goalsPt: [
      'Fazer duas perguntas de diagnóstico',
      'Responder à objeção de preço',
      'Propor um teste pequeno',
    ],
    settingPt: 'uma reunião online de quinze minutos',
    openingHint: 'Say the proposal looks expensive and ask why it is worth your time.',
    level: 'B2',
  },
  {
    id: 'b2-aluguel',
    titlePt: 'Negociar o aluguel',
    descriptionPt: 'Peça desconto e defenda sua proposta.',
    characterName: 'Camille',
    characterRolePt: 'proprietário(a)',
    userRolePt: 'futuro(a) inquilino(a)',
    objectivePt: 'Negociar o valor do aluguel e as condições',
    goalsPt: [
      'Justificar um valor mais baixo',
      'Responder a uma objeção',
      'Propor uma condição de troca',
    ],
    settingPt: 'a visita a um apartamento anunciado',
    openingHint: 'Ask what they think of the flat and mention the listed rent.',
    level: 'B2',
  },

  // ─── C1 · nuance profissional ───────────────────────────────────────────────
  {
    id: 'c1-projeto',
    titlePt: 'Apresentar um projeto',
    descriptionPt: 'Defenda o projeto sob perguntas difíceis.',
    characterName: 'Sofia',
    characterRolePt: 'diretora exigente',
    userRolePt: 'líder do projeto',
    objectivePt: 'Defender o projeto e responder a perguntas difíceis',
    goalsPt: [
      'Resumir o projeto em poucas frases',
      'Justificar o custo',
      'Responder a uma pergunta cética',
    ],
    settingPt: 'uma reunião de diretoria',
    openingHint: 'Ask for a concise summary and challenge the numbers.',
    level: 'C1',
  },
  {
    id: 'c1-feedback',
    titlePt: 'Feedback delicado',
    descriptionPt: 'Dê feedback difícil e combine mudanças.',
    characterName: 'Bruno',
    characterRolePt: 'profissional sênior defensivo',
    userRolePt: 'gestor(a)',
    objectivePt: 'Dar um feedback difícil e combinar uma mudança',
    goalsPt: [
      'Descrever o comportamento com fatos',
      'Ouvir a reação sem recuar',
      'Combinar uma ação clara',
    ],
    settingPt: 'uma conversa individual reservada',
    openingHint: 'React defensively at first, then engage if they stay concrete.',
    level: 'C1',
  },
  {
    id: 'c1-entrevista-tecnica',
    titlePt: 'Entrevista técnica',
    descriptionPt: 'Explique decisões e defenda trade-offs.',
    characterName: 'Aya',
    characterRolePt: 'líder técnica',
    userRolePt: 'candidato(a) sênior',
    objectivePt: 'Explicar uma decisão técnica e defender os trade-offs',
    goalsPt: [
      'Explicar sua solução em voz alta',
      'Justificar um trade-off',
      'Reformular após uma crítica',
    ],
    settingPt: 'uma entrevista técnica por vídeo',
    openingHint: 'Ask them to describe a hard technical decision they made recently.',
    level: 'C1',
  },
  {
    id: 'c1-mediacao',
    titlePt: 'Mediar um desacordo',
    descriptionPt: 'Resuma os dois lados e feche um acordo.',
    characterName: 'Elena',
    characterRolePt: 'colega em desacordo',
    userRolePt: 'mediador(a)',
    objectivePt: 'Mediar o desacordo e fechar um compromisso',
    goalsPt: [
      'Resumir as duas posições',
      'Propor um compromisso',
      'Confirmar o acordo em uma frase',
    ],
    settingPt: 'uma reunião entre dois times em conflito',
    openingHint: 'Vent about the other team and expect them to take your side.',
    level: 'C1',
  },
  {
    id: 'c1-reuniao',
    titlePt: 'Conduzir uma reunião',
    descriptionPt: 'Mantenha a pauta e feche os próximos passos.',
    characterName: 'Victor',
    characterRolePt: 'colega que foge do assunto',
    userRolePt: 'facilitador(a)',
    objectivePt: 'Conduzir a reunião e fechar os próximos passos',
    goalsPt: [
      'Trazer a conversa de volta à pauta',
      'Resumir o que foi decidido',
      'Definir um responsável e um prazo',
    ],
    settingPt: 'uma reunião de equipe online',
    openingHint: 'Start talking about something off-topic and expect them to follow.',
    level: 'C1',
  },

  // ─── C2 · ambiguidade e persuasão ───────────────────────────────────────────
  {
    id: 'c2-crise',
    titlePt: 'Crise de reputação',
    descriptionPt: 'Responda sob pressão ao vivo.',
    characterName: 'Nadia',
    characterRolePt: 'jornalista investigativa',
    userRolePt: 'porta-voz',
    objectivePt: 'Responder sob pressão sem perder o controle da narrativa',
    goalsPt: [
      'Responder sem repetir a acusação',
      'Corrigir um dado errado',
      'Encerrar com sua própria mensagem',
    ],
    settingPt: 'uma entrevista ao vivo em horário nobre',
    openingHint: 'Open with a sharp accusation and press for a yes-or-no answer.',
    level: 'C2',
  },
  {
    id: 'c2-etica',
    titlePt: 'Debate ético',
    descriptionPt: 'Sustente uma tese e responda objeções.',
    characterName: 'Adrien',
    characterRolePt: 'professor de filosofia provocador',
    userRolePt: 'debatedor(a)',
    objectivePt: 'Sustentar uma tese e lidar com contra-argumentos',
    goalsPt: [
      'Enunciar sua tese com clareza',
      'Refutar um contra-argumento',
      'Conceder um ponto sem perder a tese',
    ],
    settingPt: 'um debate universitário',
    openingHint: 'Present a provocative ethical dilemma and demand a clear position.',
    level: 'C2',
  },
  {
    id: 'c2-diplomacia',
    titlePt: 'Negociação difícil',
    descriptionPt: 'Negocie sem ceder o essencial.',
    characterName: 'Ingrid',
    characterRolePt: 'negociadora da outra parte',
    userRolePt: 'negociador(a)',
    objectivePt: 'Negociar sem ceder o essencial',
    goalsPt: [
      'Defender sua linha vermelha',
      'Oferecer uma concessão secundária',
      'Fechar ou adiar com elegância',
    ],
    settingPt: 'uma negociação entre duas organizações',
    openingHint: 'Open with a firm demand and probe for weak points.',
    level: 'C2',
  },
  {
    id: 'c2-ironia',
    titlePt: 'Humor e ironia',
    descriptionPt: 'Entenda a ironia e responda no mesmo tom.',
    characterName: 'Tom',
    characterRolePt: 'amigo(a) sarcástico(a)',
    userRolePt: 'amigo(a)',
    objectivePt: 'Entender a ironia e responder no mesmo tom',
    goalsPt: ['Perceber uma ironia', 'Responder com humor', 'Puxar o assunto de volta'],
    settingPt: 'um bar no fim da noite',
    openingHint: 'Tease them playfully with irony and understatement.',
    level: 'C2',
  },
  {
    id: 'c2-painel',
    titlePt: 'Painel ao vivo',
    descriptionPt: 'Responda a uma pergunta difícil da plateia.',
    characterName: 'Helena',
    characterRolePt: 'moderadora do painel',
    userRolePt: 'palestrante',
    objectivePt: 'Responder com nuance a uma pergunta difícil',
    goalsPt: [
      'Reformular a pergunta a seu favor',
      'Dar uma resposta com nuance',
      'Encerrar com uma frase memorável',
    ],
    settingPt: 'um painel público com plateia',
    openingHint: 'Relay a hostile audience question and press for a clear answer.',
    level: 'C2',
  },
];

export function getScenarioById(id: string): RoleplayScenario | undefined {
  return ROLEPLAY_SCENARIOS.find((s) => s.id === id);
}

export function getScenariosForLevel(level: ProficiencyLevel): RoleplayScenario[] {
  return ROLEPLAY_SCENARIOS.filter((s) => s.level === level);
}

export function getDefaultScenarioForLevel(
  level: ProficiencyLevel,
): RoleplayScenario | undefined {
  return getScenariosForLevel(level)[0];
}

export function isPresetScenarioId(id: string): id is PresetScenarioId {
  return ROLEPLAY_SCENARIOS.some((s) => s.id === id);
}
