import type { LessonDefinition } from '@/types';

export const ENGLISH_LESSONS: LessonDefinition[] = [
  // ── A1: Beginner ──────────────────────────────────────────────────────
  { id: 'en-a1-001', language: 'en', level: 'A1', grammarFocus: 'Sons do Inglês e o Alfabeto (TH, V/B, vogais longas/curtas)' },
  { id: 'en-sup-ways-01', language: 'en', level: 'A1', grammarFocus: 'Maneiras de Dizer: 10 Maneiras de Dizer Hello: Alternativas para cumprimentos em inglês do mais informal ao mais formal' },
  { id: 'en-a1-002', language: 'en', level: 'A1', grammarFocus: 'Sílabas Tônicas, Ritmo e Entonação Básica' },
  { id: 'en-sup-ways-02', language: 'en', level: 'A1', grammarFocus: 'Maneiras de Dizer: 10 Maneiras de Dizer Goodbye: Formas de se despedir com diferentes níveis de afeto e formalidade' },
  { id: 'en-a1-003', language: 'en', level: 'A1', grammarFocus: 'Saudações e Expressões Comuns (Hello, Thank you, Goodbye...)' },
  { id: 'en-sup-ways-03', language: 'en', level: 'A1', grammarFocus: 'Maneiras de Dizer: 12 Maneiras de Dizer Thank you: Formas de agradecer com registro e nível de gratidão variados' },
  { id: 'en-a1-004', language: 'en', level: 'A1', grammarFocus: 'Apresentando-se (My name is..., I am... years old)' },
  { id: 'en-sup-ways-04', language: 'en', level: 'A1', grammarFocus: 'Maneiras de Dizer: 10 Maneiras de Dizer Sorry/Excuse me: Formas de se desculpar e pedir licença em diferentes contextos' },
  { id: 'en-a1-005', language: 'en', level: 'A1', grammarFocus: 'Números de 0 a 20' },
  { id: 'en-sup-daily-01', language: 'en', level: 'A1', grammarFocus: 'Frases do Dia a Dia: Parte 1 — 20 Frases Essenciais de Boas-Vindas e Apresentação em Inglês' },
  { id: 'en-a1-006', language: 'en', level: 'A1', grammarFocus: 'Pronomes Sujeitos (I, you, he, she, it, we, they)' },
  { id: 'en-sup-daily-02', language: 'en', level: 'A1', grammarFocus: 'Frases do Dia a Dia: Parte 2 — 20 Frases de Pedidos e Agradecimentos em Inglês' },
  { id: 'en-a1-007', language: 'en', level: 'A1', grammarFocus: 'O verbo To Be no presente (Afirmativa)' },
  { id: 'en-sup-daily-03', language: 'en', level: 'A1', grammarFocus: 'Frases do Dia a Dia: Parte 3 — 20 Frases para Fazer Compras e Pedir Informações em Inglês' },
  { id: 'en-a1-008', language: 'en', level: 'A1', grammarFocus: 'O verbo To Be no presente (Negativa e Interrogativa)' },
  { id: 'en-sup-daily-04', language: 'en', level: 'A1', grammarFocus: 'Frases do Dia a Dia: Parte 4 — 20 Frases para Restaurantes e Bares em Inglês' },
  { id: 'en-a1-009', language: 'en', level: 'A1', grammarFocus: 'O verbo To Have (Possessão)' },
  { id: 'en-sup-vocab-07', language: 'en', level: 'A1', grammarFocus: 'Vocabulário: Pela Casa (Cômodos, móveis, eletrodomésticos)' },
  { id: 'en-a1-010', language: 'en', level: 'A1', grammarFocus: 'Artigos Definidos e Indefinidos (A, An, The)' },
  { id: 'en-sup-homo-01', language: 'en', level: 'A1', grammarFocus: 'Homófonos: there — their — they\'re' },
  { id: 'en-a1-011', language: 'en', level: 'A1', grammarFocus: 'Gênero e Plural dos Substantivos (Regulares adicionando -s)' },
  { id: 'en-sup-homo-02', language: 'en', level: 'A1', grammarFocus: 'Homófonos: to — too — two' },
  { id: 'en-a1-012', language: 'en', level: 'A1', grammarFocus: 'Plurais Irregulares Básicos (men, women, children, teeth)' },
  { id: 'en-sup-homo-03', language: 'en', level: 'A1', grammarFocus: 'Homófonos: hear — here' },
  { id: 'en-a1-013', language: 'en', level: 'A1', grammarFocus: 'Cores e Formas Básicas' },
  { id: 'en-sup-homo-04', language: 'en', level: 'A1', grammarFocus: 'Homófonos: know — no' },
  { id: 'en-a1-014', language: 'en', level: 'A1', grammarFocus: 'Adjetivos Comuns e seus Opostos (Big/small, hot/cold)' },
  { id: 'en-sup-homo-05', language: 'en', level: 'A1', grammarFocus: 'Homófonos: write — right — rite' },
  { id: 'en-a1-015', language: 'en', level: 'A1', grammarFocus: 'Posição dos Adjetivos (Antes do substantivo)' },
  { id: 'en-sup-homo-06', language: 'en', level: 'A1', grammarFocus: 'Homófonos: by — buy — bye' },
  { id: 'en-a1-016', language: 'en', level: 'A1', grammarFocus: 'Números de 21 a 100' },
  { id: 'en-sup-homo-07', language: 'en', level: 'A1', grammarFocus: 'Homófonos: week — weak' },
  { id: 'en-a1-017', language: 'en', level: 'A1', grammarFocus: 'Dias da Semana' },
  { id: 'en-sup-homo-08', language: 'en', level: 'A1', grammarFocus: 'Homófonos: meet — meat — mete' },
  { id: 'en-a1-018', language: 'en', level: 'A1', grammarFocus: 'Meses do Ano' },
  { id: 'en-sup-homo-09', language: 'en', level: 'A1', grammarFocus: 'Homófonos: sun — son' },
  { id: 'en-a1-019', language: 'en', level: 'A1', grammarFocus: 'There is / There are (Haver / Existir no presente)' },
  { id: 'en-sup-homo-10', language: 'en', level: 'A1', grammarFocus: 'Homófonos: pear — pair — pare' },
  { id: 'en-a1-020', language: 'en', level: 'A1', grammarFocus: 'Preposições de Lugar (In, On, At)' },
  { id: 'en-sup-homo-11', language: 'en', level: 'A1', grammarFocus: 'Homófonos: bear — bare' },
  { id: 'en-a1-021', language: 'en', level: 'A1', grammarFocus: 'Lugares na Cidade' },
  { id: 'en-sup-homo-12', language: 'en', level: 'A1', grammarFocus: 'Homófonos: wear — where — ware' },
  { id: 'en-a1-022', language: 'en', level: 'A1', grammarFocus: 'Simple Present: I, You, We, They (Hábitos e rotinas)' },
  { id: 'en-sup-homo-13', language: 'en', level: 'A1', grammarFocus: 'Homófonos: wait — weight' },
  { id: 'en-a1-023', language: 'en', level: 'A1', grammarFocus: 'Simple Present: He, She, It (Adicionando -s / -es)' },
  { id: 'en-sup-homo-14', language: 'en', level: 'A1', grammarFocus: 'Homófonos: sail — sale' },
  { id: 'en-a1-024', language: 'en', level: 'A1', grammarFocus: 'Negação Básica no Simple Present (Don\'t / Doesn\'t)' },
  { id: 'en-sup-homo-15', language: 'en', level: 'A1', grammarFocus: 'Homófonos: mail — male' },
  { id: 'en-a1-025', language: 'en', level: 'A1', grammarFocus: 'Perguntas no Simple Present (Do / Does)' },
  { id: 'en-sup-homo-16', language: 'en', level: 'A1', grammarFocus: 'Homófonos: tale — tail' },
  { id: 'en-a1-026', language: 'en', level: 'A1', grammarFocus: 'Adjetivos Possessivos (My, your, his, her, its, our, their)' },
  { id: 'en-sup-homo-17', language: 'en', level: 'A1', grammarFocus: 'Homófonos: hair — hare' },
  { id: 'en-a1-027', language: 'en', level: 'A1', grammarFocus: 'O Genitivo \'S (John\'s car) vs. Of (The door of the car)' },
  { id: 'en-sup-homo-18', language: 'en', level: 'A1', grammarFocus: 'Homófonos: blue — blew' },
  { id: 'en-a1-028', language: 'en', level: 'A1', grammarFocus: 'Adjetivos Demonstrativos (This, That, These, Those)' },
  { id: 'en-sup-homo-19', language: 'en', level: 'A1', grammarFocus: 'Homófonos: new — knew' },
  { id: 'en-a1-029', language: 'en', level: 'A1', grammarFocus: 'Palavras Interrogativas: What, Who, Where' },
  { id: 'en-sup-homo-20', language: 'en', level: 'A1', grammarFocus: 'Homófonos: aloud — allowed' },
  { id: 'en-a1-030', language: 'en', level: 'A1', grammarFocus: 'Palavras Interrogativas: When, Why, How' },
  { id: 'en-sup-homo-21', language: 'en', level: 'A1', grammarFocus: 'Homófonos: brake — break' },
  { id: 'en-a1-031', language: 'en', level: 'A1', grammarFocus: 'Dizendo as Horas (Horas e Minutos)' },
  { id: 'en-sup-homo-22', language: 'en', level: 'A1', grammarFocus: 'Homófonos: flour — flower' },
  { id: 'en-a1-032', language: 'en', level: 'A1', grammarFocus: 'Países e Nacionalidades Básicas' },
  { id: 'en-sup-homo-23', language: 'en', level: 'A1', grammarFocus: 'Homófonos: knight — night' },
  { id: 'en-a1-033', language: 'en', level: 'A1', grammarFocus: 'Advérbios de Frequência (Always, usually, sometimes, never)' },
  { id: 'en-sup-homo-24', language: 'en', level: 'A1', grammarFocus: 'Homófonos: hole — whole' },
  { id: 'en-a1-034', language: 'en', level: 'A1', grammarFocus: 'Modal Verb: Can / Can\'t (Habilidade e Permissão)' },
  { id: 'en-a1-035', language: 'en', level: 'A1', grammarFocus: 'Present Continuous (Am/Is/Are + -ing) — Ações acontecendo agora' },
  { id: 'en-a1-036', language: 'en', level: 'A1', grammarFocus: 'Present Continuous vs. Simple Present' },
  { id: 'en-a1-037', language: 'en', level: 'A1', grammarFocus: 'Vocabulário de Rotina Diária e Collocations' },
  { id: 'en-a1-038', language: 'en', level: 'A1', grammarFocus: 'Membros da Família e Relacionamentos' },
  { id: 'en-a1-039', language: 'en', level: 'A1', grammarFocus: 'Clima e Estações do Ano' },
  { id: 'en-a1-040', language: 'en', level: 'A1', grammarFocus: 'Vocabulário de Comida — Refeições e Básicos' },
  { id: 'en-a1-041', language: 'en', level: 'A1', grammarFocus: 'Substantivos Contáveis e Incontáveis' },
  { id: 'en-a1-042', language: 'en', level: 'A1', grammarFocus: 'Quantificadores: Some vs. Any' },
  { id: 'en-a1-043', language: 'en', level: 'A1', grammarFocus: 'Quantificadores: How much vs. How many' },
  { id: 'en-a1-044', language: 'en', level: 'A1', grammarFocus: 'Phrasal Verbs Básicos para Iniciantes (Wake up, stand up, sit down)' },
  { id: 'en-a1-045', language: 'en', level: 'A1', grammarFocus: 'Expressões de sobrevivência do dia a dia em inglês: Excuse me, I don\'t understand, Can you repeat that?, How much is it?, Where is the bathroom?, I would like..., Sorry about that, Thank you very much, Nice to meet you, See you later' },

  // ── A2: Elementary ──────────────────────────────────────────────────
  { id: 'en-a2-046', language: 'en', level: 'A2', grammarFocus: 'Pronomes de Objeto (Me, him, her, us, them)' },
  { id: 'en-sup-ways-05', language: 'en', level: 'A2', grammarFocus: 'Maneiras de Dizer: 8 Maneiras de Dizer I don\'t know: Alternativas naturais para expressar desconhecimento ou incerteza' },
  { id: 'en-a2-047', language: 'en', level: 'A2', grammarFocus: 'O verbo To Be no passado (Was / Were)' },
  { id: 'en-sup-ways-10', language: 'en', level: 'A2', grammarFocus: 'Maneiras de Dizer: 10 Maneiras de Dizer How are you?: Alternativas para perguntar como a pessoa está em inglês' },
  { id: 'en-a2-048', language: 'en', level: 'A2', grammarFocus: 'Simple Past: Verbos Regulares (Regras de pronúncia -ed)' },
  { id: 'en-sup-ways-11', language: 'en', level: 'A2', grammarFocus: 'Maneiras de Dizer: 12 Maneiras de Dizer I\'m fine: Respostas variadas e naturais para \'Como vai?\' em inglês' },
  { id: 'en-a2-049', language: 'en', level: 'A2', grammarFocus: 'Simple Past: Verbos Irregulares Principais (Parte 1: Go, do, have, make)' },
  { id: 'en-sup-ways-12', language: 'en', level: 'A2', grammarFocus: 'Maneiras de Dizer: 8 Maneiras de Dizer Good luck: Formas de desejar boa sorte com registro variado' },
  { id: 'en-a2-050', language: 'en', level: 'A2', grammarFocus: 'Simple Past: Verbos Irregulares Principais (Parte 2: Say, see, get, take)' },
  { id: 'en-sup-ways-13', language: 'en', level: 'A2', grammarFocus: 'Maneiras de Dizer: 10 Maneiras de Dizer Congratulations: Formas de parabenizar com contexto e ênfase variados' },
  { id: 'en-a2-051', language: 'en', level: 'A2', grammarFocus: 'Negação e Perguntas no Simple Past (Did / Didn\'t)' },
  { id: 'en-sup-ways-14', language: 'en', level: 'A2', grammarFocus: 'Maneiras de Dizer: 8 Maneiras de Dizer That\'s great!: Expressões entusiastas para reagir a boas notícias em inglês' },
  { id: 'en-a2-052', language: 'en', level: 'A2', grammarFocus: 'Adjetivos Comparativos (Taller than, more expensive than)' },
  { id: 'en-sup-daily-05', language: 'en', level: 'A2', grammarFocus: 'Frases do Dia a Dia: Parte 5 — 20 Frases de Transporte e Orientação em Inglês' },
  { id: 'en-a2-053', language: 'en', level: 'A2', grammarFocus: 'Adjetivos Superlativos (The tallest, the most expensive)' },
  { id: 'en-sup-daily-06', language: 'en', level: 'A2', grammarFocus: 'Frases do Dia a Dia: Parte 6 — 20 Frases de Trabalho e Ambiente Profissional em Inglês' },
  { id: 'en-a2-054', language: 'en', level: 'A2', grammarFocus: 'Estruturas com As... as para igualdade' },
  { id: 'en-sup-daily-07', language: 'en', level: 'A2', grammarFocus: 'Frases do Dia a Dia: Parte 7 — 20 Frases de Situações de Emergência e Saúde em Inglês' },
  { id: 'en-a2-055', language: 'en', level: 'A2', grammarFocus: 'Planos futuros com Going To' },
  { id: 'en-sup-vocab-02', language: 'en', level: 'A2', grammarFocus: 'Vocabulário: No Restaurante (Pedindo comida, reclamações, pagamento)' },
  { id: 'en-a2-056', language: 'en', level: 'A2', grammarFocus: 'Previsões e promessas futuras com Will' },
  { id: 'en-sup-conf-01', language: 'en', level: 'A2', grammarFocus: 'Confusão: Make VS Do' },
  { id: 'en-a2-057', language: 'en', level: 'A2', grammarFocus: 'Will vs. Going To (Decisões espontâneas vs. Planos)' },
  { id: 'en-sup-conf-02', language: 'en', level: 'A2', grammarFocus: 'Confusão: Say VS Tell' },
  { id: 'en-a2-058', language: 'en', level: 'A2', grammarFocus: 'Modal Verb: Should / Shouldn\'t (Dando conselhos)' },
  { id: 'en-sup-conf-03', language: 'en', level: 'A2', grammarFocus: 'Confusão: Hear VS Listen (to)' },
  { id: 'en-a2-059', language: 'en', level: 'A2', grammarFocus: 'Expressando Obrigação: Have to vs. Must' },
  { id: 'en-sup-conf-04', language: 'en', level: 'A2', grammarFocus: 'Confusão: See VS Watch VS Look (at)' },
  { id: 'en-a2-060', language: 'en', level: 'A2', grammarFocus: 'Expressando Falta de Obrigação: Don\'t have to' },
  { id: 'en-sup-conf-05', language: 'en', level: 'A2', grammarFocus: 'Confusão: Bring VS Take' },
  { id: 'en-a2-061', language: 'en', level: 'A2', grammarFocus: 'Modal Verb: Would like to (Pedidos e ofertas educados)' },
  { id: 'en-sup-conf-06', language: 'en', level: 'A2', grammarFocus: 'Confusão: Borrow VS Lend' },
  { id: 'en-a2-062', language: 'en', level: 'A2', grammarFocus: 'Pronomes: Something, Anything, Nothing, Everything' },
  { id: 'en-sup-conf-07', language: 'en', level: 'A2', grammarFocus: 'Confusão: Affect VS Effect' },
  { id: 'en-a2-063', language: 'en', level: 'A2', grammarFocus: 'Pronomes: Someone, Anyone, No one, Everyone' },
  { id: 'en-sup-conf-08', language: 'en', level: 'A2', grammarFocus: 'Confusão: Accept VS Except' },
  { id: 'en-a2-064', language: 'en', level: 'A2', grammarFocus: 'Conjunções Básicas (And, but, so, because)' },
  { id: 'en-sup-conf-09', language: 'en', level: 'A2', grammarFocus: 'Confusão: Advice VS Advise' },
  { id: 'en-a2-065', language: 'en', level: 'A2', grammarFocus: 'Advérbios de Modo (Adicionando -ly)' },
  { id: 'en-sup-conf-10', language: 'en', level: 'A2', grammarFocus: 'Confusão: Complement VS Compliment' },
  { id: 'en-a2-066', language: 'en', level: 'A2', grammarFocus: 'Modificadores de Advérbio (Very, really, quite, too)' },
  { id: 'en-sup-conf-11', language: 'en', level: 'A2', grammarFocus: 'Confusão: Desert VS Dessert' },
  { id: 'en-a2-067', language: 'en', level: 'A2', grammarFocus: 'Collocations com Make vs. Do (Parte 1)' },
  { id: 'en-sup-conf-12', language: 'en', level: 'A2', grammarFocus: 'Confusão: Lose VS Loose' },
  { id: 'en-a2-068', language: 'en', level: 'A2', grammarFocus: 'Phrasal Verbs de Conversação: Olhar (Look at, look for, look after)' },
  { id: 'en-sup-conf-13', language: 'en', level: 'A2', grammarFocus: 'Confusão: Then VS Than' },
  { id: 'en-a2-069', language: 'en', level: 'A2', grammarFocus: 'Phrasal Verbs de Conversação: Transporte (Get in, get out, get on, get off)' },
  { id: 'en-sup-conf-14', language: 'en', level: 'A2', grammarFocus: 'Confusão: Fewer VS Less' },
  { id: 'en-a2-070', language: 'en', level: 'A2', grammarFocus: 'Expressões de quantidade: A lot of, many, much, a few, a little' },
  { id: 'en-sup-conf-15', language: 'en', level: 'A2', grammarFocus: 'Confusão: Who VS Whom' },
  { id: 'en-a2-071', language: 'en', level: 'A2', grammarFocus: 'Exclamações: What a...! e How...!' },
  { id: 'en-sup-conf-16', language: 'en', level: 'A2', grammarFocus: 'Confusão: Lay VS Lie' },
  { id: 'en-a2-072', language: 'en', level: 'A2', grammarFocus: 'Direções e Navegação na Cidade' },
  { id: 'en-sup-conf-17', language: 'en', level: 'A2', grammarFocus: 'Confusão: Raise VS Rise' },
  { id: 'en-a2-073', language: 'en', level: 'A2', grammarFocus: 'Padrões de Verbo: Verbo + Infinitivo (Want to, hope to, need to)' },
  { id: 'en-sup-conf-18', language: 'en', level: 'A2', grammarFocus: 'Confusão: Sit VS Set' },
  { id: 'en-a2-074', language: 'en', level: 'A2', grammarFocus: 'Padrões de Verbo: Verbo + Gerúndio (Enjoy reading, finish eating)' },
  { id: 'en-sup-conf-19', language: 'en', level: 'A2', grammarFocus: 'Confusão: Farther VS Further' },
  { id: 'en-a2-075', language: 'en', level: 'A2', grammarFocus: 'O Infinitivo de Finalidade (Infinitive of Purpose)' },
  { id: 'en-sup-conf-20', language: 'en', level: 'A2', grammarFocus: 'Confusão: Continual VS Continuous' },
  { id: 'en-a2-076', language: 'en', level: 'A2', grammarFocus: 'O Imperativo (Dando instruções e avisos)' },
  { id: 'en-sup-conf-21', language: 'en', level: 'A2', grammarFocus: 'Confusão: Imply VS Infer' },
  { id: 'en-a2-077', language: 'en', level: 'A2', grammarFocus: 'Present Continuous para Compromissos Futuros' },
  { id: 'en-sup-conf-22', language: 'en', level: 'A2', grammarFocus: 'Confusão: That VS Which (Orações restritivas vs. não restritivas)' },
  { id: 'en-a2-078', language: 'en', level: 'A2', grammarFocus: 'Preenchedores de Conversação (Well, you know, like)' },
  { id: 'en-sup-conf-23', language: 'en', level: 'A2', grammarFocus: 'Confusão: Since VS For (Expressões de tempo)' },
  { id: 'en-a2-079', language: 'en', level: 'A2', grammarFocus: 'Idiomatismos sobre Emoções' },
  { id: 'en-sup-conf-24', language: 'en', level: 'A2', grammarFocus: 'Confusão: Ago VS Before' },
  { id: 'en-a2-080', language: 'en', level: 'A2', grammarFocus: 'Respostas naturais em conversação (Me too, Me neither)' },
  { id: 'en-sup-conf-25', language: 'en', level: 'A2', grammarFocus: 'Confusão: Already VS Yet VS Still' },
  { id: 'en-a2-081', language: 'en', level: 'A2', grammarFocus: 'Números de 101 a 1.000.000.000 e Números Ordinais' },
  { id: 'en-sup-conf-26', language: 'en', level: 'A2', grammarFocus: 'Confusão: Another VS Other VS Others VS The Other(s)' },
  { id: 'en-a2-082', language: 'en', level: 'A2', grammarFocus: 'Empregos e Profissões' },
  { id: 'en-sup-conf-27', language: 'en', level: 'A2', grammarFocus: 'Confusão: So VS Such' },
  { id: 'en-a2-083', language: 'en', level: 'A2', grammarFocus: 'Partes do Corpo e Saúde' },
  { id: 'en-sup-conf-28', language: 'en', level: 'A2', grammarFocus: 'Confusão: Used to VS Would (Hábitos no passado)' },
  { id: 'en-a2-084', language: 'en', level: 'A2', grammarFocus: 'Esportes e Hobbies' },
  { id: 'en-sup-conf-29', language: 'en', level: 'A2', grammarFocus: 'Confusão: Also VS Too VS Either' },
  { id: 'en-a2-085', language: 'en', level: 'A2', grammarFocus: 'Falsos Cognatos Básicos (Portuguese-English Pitfalls)' },
  { id: 'en-sup-conf-30', language: 'en', level: 'A2', grammarFocus: 'Confusão: Like VS As' },
  { id: 'en-sup-conf-31', language: 'en', level: 'A2', grammarFocus: 'Confusão: Despite VS Although VS In spite of' },
  { id: 'en-sup-conf-32', language: 'en', level: 'A2', grammarFocus: 'Confusão: By VS Until (Prazos vs. Duração)' },
  { id: 'en-sup-conf-33', language: 'en', level: 'A2', grammarFocus: 'Confusão: During VS For VS While' },
  { id: 'en-sup-conf-34', language: 'en', level: 'A2', grammarFocus: 'Confusão: Maybe VS Perhaps VS Probably' },
  { id: 'en-sup-conf-35', language: 'en', level: 'A2', grammarFocus: 'Confusão: Very VS Too VS Enough' },
  { id: 'en-sup-conf-36', language: 'en', level: 'A2', grammarFocus: 'Confusão: Quite VS Rather VS Fairly' },
  { id: 'en-sup-conf-37', language: 'en', level: 'A2', grammarFocus: 'Confusão: Hard VS Hardly' },
  { id: 'en-sup-conf-38', language: 'en', level: 'A2', grammarFocus: 'Confusão: Late VS Lately' },
  { id: 'en-sup-conf-39', language: 'en', level: 'A2', grammarFocus: 'Confusão: Nearly VS Almost' },
  { id: 'en-sup-conf-40', language: 'en', level: 'A2', grammarFocus: 'Confusão: Last VS Latest VS Final VS Recent' },
  { id: 'en-sup-conf-41', language: 'en', level: 'A2', grammarFocus: 'Confusão: Fun VS Funny' },
  { id: 'en-sup-conf-42', language: 'en', level: 'A2', grammarFocus: 'Confusão: Worth VS Worthwhile VS Worthy' },
  { id: 'en-sup-conf-43', language: 'en', level: 'A2', grammarFocus: 'Confusão: Economic VS Economical' },
  { id: 'en-sup-conf-44', language: 'en', level: 'A2', grammarFocus: 'Confusão: Classic VS Classical' },
  { id: 'en-sup-conf-45', language: 'en', level: 'A2', grammarFocus: 'Confusão: Remember VS Remind' },
  { id: 'en-sup-conf-46', language: 'en', level: 'A2', grammarFocus: 'Confusão: Know VS Meet (Conhecer uma pessoa vs. Primeiros encontros)' },
  { id: 'en-sup-conf-47', language: 'en', level: 'A2', grammarFocus: 'Confusão: Speak VS Talk VS Say VS Tell' },
  { id: 'en-sup-conf-48', language: 'en', level: 'A2', grammarFocus: 'Confusão: Win VS Beat VS Earn' },
  { id: 'en-sup-conf-49', language: 'en', level: 'A2', grammarFocus: 'Confusão: Arrive VS Get to VS Reach' },
  { id: 'en-sup-conf-50', language: 'en', level: 'A2', grammarFocus: 'Confusão: Alone VS Lonely' },
  { id: 'en-sup-conf-51', language: 'en', level: 'A2', grammarFocus: 'Confusão: Especially VS Specially' },
  { id: 'en-sup-conf-52', language: 'en', level: 'A2', grammarFocus: 'Confusão: Still VS Anymore VS No longer' },
  { id: 'en-sup-conf-53', language: 'en', level: 'A2', grammarFocus: 'Confusão: Each VS Every' },
  { id: 'en-sup-conf-54', language: 'en', level: 'A2', grammarFocus: 'Confusão: Some VS Any (Usos contextuais avançados)' },
  { id: 'en-sup-conf-55', language: 'en', level: 'A2', grammarFocus: 'Confusão: Hope VS Wish' },
  { id: 'en-sup-conf-56', language: 'en', level: 'A2', grammarFocus: 'Confusão: Miss VS Lack VS Fail' },
  { id: 'en-sup-conf-57', language: 'en', level: 'A2', grammarFocus: 'Confusão: Historic VS Historical' },
  { id: 'en-sup-conf-58', language: 'en', level: 'A2', grammarFocus: 'Confusão: Childlike VS Childish' },
  { id: 'en-sup-conf-59', language: 'en', level: 'A2', grammarFocus: 'Confusão: Even though VS Even if' },
  { id: 'en-sup-conf-60', language: 'en', level: 'A2', grammarFocus: 'Confusão: In the end VS At the end' },
  { id: 'en-a2-086', language: 'en', level: 'A2', grammarFocus: 'Expressões cotidianas de opinião e reação em inglês: In my opinion, I think that, That\'s too bad, Good for you!, I don\'t mind, I heard that, I\'m fed up, It depends, Not at all, No way!' },

  // ── B1: Intermediate ─────────────────────────────────────────────────
  { id: 'en-b1-087', language: 'en', level: 'B1', grammarFocus: 'Introdução ao Present Perfect (Have/Has + Particípio Passado)' },
  { id: 'en-sup-ways-06', language: 'en', level: 'B1', grammarFocus: 'Maneiras de Dizer: 9 Maneiras de Dizer I understand: Formas de confirmar compreensão com nuances de formalidade' },
  { id: 'en-b1-088', language: 'en', level: 'B1', grammarFocus: 'Present Perfect para experiências de vida (Have you ever...?)' },
  { id: 'en-sup-ways-07', language: 'en', level: 'B1', grammarFocus: 'Maneiras de Dizer: 8 Maneiras de Dizer I don\'t understand: Expressões naturais para pedir esclarecimento em inglês' },
  { id: 'en-b1-089', language: 'en', level: 'B1', grammarFocus: 'Present Perfect vs. Simple Past (Passado inacabado vs. finalizado)' },
  { id: 'en-sup-ways-08', language: 'en', level: 'B1', grammarFocus: 'Maneiras de Dizer: 10 Maneiras de Dizer I agree: Formas de concordar com diferentes graus de ênfase' },
  { id: 'en-b1-090', language: 'en', level: 'B1', grammarFocus: 'Present Perfect com Just, Already, Yet' },
  { id: 'en-sup-ways-09', language: 'en', level: 'B1', grammarFocus: 'Maneiras de Dizer: 8 Maneiras de Dizer I disagree (Politely): Formas educadas de discordar em inglês' },
  { id: 'en-b1-091', language: 'en', level: 'B1', grammarFocus: 'Present Perfect com For e Since' },
  { id: 'en-sup-idiom-01', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Break a leg! (Good luck!)' },
  { id: 'en-b1-092', language: 'en', level: 'B1', grammarFocus: 'Collocations de Preposição: Adjetivos + Preposições' },
  { id: 'en-sup-idiom-02', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Hit the nail on the head (To be exactly right)' },
  { id: 'en-b1-093', language: 'en', level: 'B1', grammarFocus: 'Collocations de Preposição: Verbos + Preposições' },
  { id: 'en-sup-idiom-03', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Under the weather (Feeling sick)' },
  { id: 'en-b1-094', language: 'en', level: 'B1', grammarFocus: 'Collocations com Make vs. Do (Parte 2)' },
  { id: 'en-sup-idiom-04', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Bite off more than you can chew (To take on too much)' },
  { id: 'en-b1-095', language: 'en', level: 'B1', grammarFocus: '1ª Condicional (If + Presente, Will + Verbo)' },
  { id: 'en-sup-idiom-05', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Let the cat out of the bag (To reveal a secret)' },
  { id: 'en-b1-096', language: 'en', level: 'B1', grammarFocus: '2ª Condicional (If + Passado, Would + Verbo)' },
  { id: 'en-sup-idiom-06', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Once in a blue moon (Very rarely)' },
  { id: 'en-b1-097', language: 'en', level: 'B1', grammarFocus: 'Verbos Modais de Dedução no Presente (Must, Might, May, Can\'t)' },
  { id: 'en-sup-idiom-07', language: 'en', level: 'B1', grammarFocus: 'Expressões Idiomáticas: Burn the midnight oil (To work late into the night)' },
  { id: 'en-b1-098', language: 'en', level: 'B1', grammarFocus: 'Used to (Hábitos e estados no passado)' },
  { id: 'en-sup-vocab-01', language: 'en', level: 'B1', grammarFocus: 'Vocabulário: No Médico (Vocabulário de consultas médicas)' },
  { id: 'en-b1-099', language: 'en', level: 'B1', grammarFocus: 'Pronomes Relativos: Who, Which, That (Orações restritivas)' },
  { id: 'en-sup-vocab-03', language: 'en', level: 'B1', grammarFocus: 'Vocabulário: Compras e Dinheiro (Preços, recibos, devoluções)' },
  { id: 'en-b1-100', language: 'en', level: 'B1', grammarFocus: 'Pronomes Relativos: Whose, Where, When' },
  { id: 'en-sup-vocab-06', language: 'en', level: 'B1', grammarFocus: 'Vocabulário: Esportes e Fitness (Equipamentos, posições, ações)' },
  { id: 'en-b1-101', language: 'en', level: 'B1', grammarFocus: 'Orações Relativas Não Restritivas (Informação extra)' },
  { id: 'en-sup-write-01', language: 'en', level: 'B1', grammarFocus: 'Sugestão de Escrita: Descreva um lugar onde você se sente completamente em paz.' },
  { id: 'en-b1-102', language: 'en', level: 'B1', grammarFocus: 'Voz Passiva: Simple Present (Is made, are sold)' },
  { id: 'en-sup-write-02', language: 'en', level: 'B1', grammarFocus: 'Sugestão de Escrita: Quais são as vantagens e desvantagens das redes sociais?' },
  { id: 'en-b1-103', language: 'en', level: 'B1', grammarFocus: 'Voz Passiva: Simple Past (Was built, were written)' },
  { id: 'en-b1-104', language: 'en', level: 'B1', grammarFocus: 'So... that e Such... that (Causa e efeito)' },
  { id: 'en-b1-105', language: 'en', level: 'B1', grammarFocus: 'Both, Either, Neither' },
  { id: 'en-b1-106', language: 'en', level: 'B1', grammarFocus: 'Introdução à Forma Causativa (Have / Get something done)' },
  { id: 'en-b1-107', language: 'en', level: 'B1', grammarFocus: 'Phrasal Verbs com Get (Get up, get back, get over)' },
  { id: 'en-b1-108', language: 'en', level: 'B1', grammarFocus: 'Phrasal Verbs com Take (Take off, take up, take out, take back)' },
  { id: 'en-b1-109', language: 'en', level: 'B1', grammarFocus: 'Phrasal Verbs com Turn (Turn on, turn off, turn up, turn down)' },
  { id: 'en-b1-110', language: 'en', level: 'B1', grammarFocus: 'Phrasal Verbs: Estruturas Separáveis vs. Inseparáveis' },
  { id: 'en-b1-111', language: 'en', level: 'B1', grammarFocus: 'Idiomatismos de Conversação: Tempo (Beat the clock, around the clock)' },
  { id: 'en-b1-112', language: 'en', level: 'B1', grammarFocus: 'Idiomatismos de Conversação: Dinheiro (Costs an arm and a leg)' },
  { id: 'en-b1-113', language: 'en', level: 'B1', grammarFocus: 'Idiomatismos de Conversação: Comida e Natureza (Spill the beans)' },
  { id: 'en-b1-114', language: 'en', level: 'B1', grammarFocus: 'Question Tags (You\'re Brazilian, aren\'t you?)' },
  { id: 'en-b1-115', language: 'en', level: 'B1', grammarFocus: 'Concordando e discordando naturalmente (I couldn\'t agree more)' },
  { id: 'en-b1-116', language: 'en', level: 'B1', grammarFocus: 'Respostas curtas em conversas (So do I, Neither do I)' },
  { id: 'en-b1-117', language: 'en', level: 'B1', grammarFocus: 'Palavras de Ligação para Contraste (Although, even though, however)' },
  { id: 'en-b1-118', language: 'en', level: 'B1', grammarFocus: 'Palavras de Ligação para Razão e Resultado (Therefore, as a result, due to)' },
  { id: 'en-b1-119', language: 'en', level: 'B1', grammarFocus: 'Collocations de Viagens e Aeroportos' },
  { id: 'en-b1-120', language: 'en', level: 'B1', grammarFocus: 'Collocations de Trabalho e Negócios' },
  { id: 'en-b1-121', language: 'en', level: 'B1', grammarFocus: 'Frases de esclarecimento em conversação (What I mean is...)' },
  { id: 'en-b1-122', language: 'en', level: 'B1', grammarFocus: 'Expressões idiomáticas intermediárias do inglês cotidiano: Hit the nail on the head, Under the weather, Break a leg, Cost an arm and a leg, Once in a blue moon, Get cold feet, Beat around the bush, Bite off more than you can chew, Jump on the bandwagon, Let the cat out of the bag' },

  // ── B2: Upper-Intermediate ──────────────────────────────────────────
  { id: 'en-b2-123', language: 'en', level: 'B2', grammarFocus: 'Present Perfect Continuous (Have been doing)' },
  { id: 'en-sup-write-03', language: 'en', level: 'B2', grammarFocus: 'Sugestão de Escrita: Imagine que você pudesse viajar no tempo. Para onde iria e por que?' },
  { id: 'en-b2-124', language: 'en', level: 'B2', grammarFocus: 'Present Perfect Simple vs. Continuous (Duração vs. Resultado)' },
  { id: 'en-sup-write-04', language: 'en', level: 'B2', grammarFocus: 'Sugestão de Escrita: Como você vê sua vida em dez anos?' },
  { id: 'en-b2-125', language: 'en', level: 'B2', grammarFocus: 'O Past Perfect (Had done)' },
  { id: 'en-sup-write-05', language: 'en', level: 'B2', grammarFocus: 'Sugestão de Escrita: Descreva um desafio que você superou e o que aprendeu com ele.' },
  { id: 'en-b2-126', language: 'en', level: 'B2', grammarFocus: 'Conectando narrativas: Simple Past, Past Continuous, e Past Perfect' },
  { id: 'en-sup-write-06', language: 'en', level: 'B2', grammarFocus: 'Sugestão de Escrita: Escreva sobre seu melhor amigo e uma memória especial que vocês compartilham.' },
  { id: 'en-b2-127', language: 'en', level: 'B2', grammarFocus: '3ª Condicional (If I had known, I would have gone)' },
  { id: 'en-sup-write-07', language: 'en', level: 'B2', grammarFocus: 'Sugestão de Escrita: Descreva uma pessoa que teve um impacto significativo na sua vida.' },
  { id: 'en-b2-128', language: 'en', level: 'B2', grammarFocus: 'Desejos e Arrependimentos no presente (I wish I were...)' },
  { id: 'en-sup-vocab-04', language: 'en', level: 'B2', grammarFocus: 'Vocabulário: Trabalho e Escritório (Reuniões, tarefas, funções)' },
  { id: 'en-b2-129', language: 'en', level: 'B2', grammarFocus: 'Arrependimentos no passado (I wish I had known...)' },
  { id: 'en-sup-vocab-05', language: 'en', level: 'B2', grammarFocus: 'Vocabulário: Tecnologia e Redes Sociais (Apps, dispositivos, vida online)' },
  { id: 'en-b2-130', language: 'en', level: 'B2', grammarFocus: 'Discurso Indireto (Reported Speech): Afirmações' },
  { id: 'en-sup-expr-01', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Get: Phrasal verbs e idioms com get em inglês cotidiano' },
  { id: 'en-b2-131', language: 'en', level: 'B2', grammarFocus: 'Discurso Indireto (Reported Speech): Perguntas' },
  { id: 'en-sup-expr-02', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Make: Usos figurados de make em situações reais' },
  { id: 'en-b2-132', language: 'en', level: 'B2', grammarFocus: 'Discurso Indireto (Reported Speech): Comandos e Pedidos' },
  { id: 'en-sup-expr-03', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Do: Expressões cotidianas e idiomáticas com do' },
  { id: 'en-b2-133', language: 'en', level: 'B2', grammarFocus: 'Voz Passiva Avançada (Has been done, will be built)' },
  { id: 'en-sup-expr-04', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Take: Idioms com take para descever ações e atitudes' },
  { id: 'en-b2-134', language: 'en', level: 'B2', grammarFocus: 'Voz Passiva com Verbos de Relato (It is said that...)' },
  { id: 'en-sup-expr-05', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Give: Usos idiomáticos de give para expressões de ceder, presentear e reagir' },
  { id: 'en-b2-135', language: 'en', level: 'B2', grammarFocus: 'Verbos Modais de Dedução no Passado (Must have, might have, can\'t have)' },
  { id: 'en-sup-expr-06', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Have: Expressões com have que vão além da posse simples' },
  { id: 'en-b2-136', language: 'en', level: 'B2', grammarFocus: 'Arrependimentos e Críticas com Modais (Should have done, ought to have done)' },
  { id: 'en-sup-expr-07', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Run: Idioms com run para velocidade, exaustão e operações' },
  { id: 'en-b2-137', language: 'en', level: 'B2', grammarFocus: 'Future Continuous (Will be doing)' },
  { id: 'en-sup-expr-08', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Break: Phrasal verbs e idioms com break para rupturas e oportunidades' },
  { id: 'en-b2-138', language: 'en', level: 'B2', grammarFocus: 'Future Perfect (Will have done)' },
  { id: 'en-sup-expr-09', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Come: Idioms com come para progresso, resultados e aproximação' },
  { id: 'en-b2-139', language: 'en', level: 'B2', grammarFocus: 'Be used to vs. Get used to (+ substantivo / -ing)' },
  { id: 'en-sup-expr-10', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Turn: Idioms com turn para mudanças e reversões' },
  { id: 'en-b2-140', language: 'en', level: 'B2', grammarFocus: 'Adjetivos Extremos e modificadores (Absolutely exhausted)' },
  { id: 'en-sup-expr-11', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Set: Usos idiomáticos de set para metas, armadilhas e inicíos' },
  { id: 'en-b2-141', language: 'en', level: 'B2', grammarFocus: 'Adjetivos Participiais (-ed vs. -ing)' },
  { id: 'en-sup-expr-12', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Go: Idioms com go para movimento, progressão e decisões' },
  { id: 'en-b2-142', language: 'en', level: 'B2', grammarFocus: 'Even, Even if, Even though, As though' },
  { id: 'en-sup-expr-13', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Keep: Idioms com keep para persistência e controle' },
  { id: 'en-b2-143', language: 'en', level: 'B2', grammarFocus: 'Expressando probabilidade (Bound to, likely to, highly unlikely)' },
  { id: 'en-sup-expr-14', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Hold: Idioms com hold para controle, espera e resistência' },
  { id: 'en-b2-144', language: 'en', level: 'B2', grammarFocus: 'Collocations Fortes: Adjetivos Amplificadores (Heavy rain, strict rules)' },
  { id: 'en-sup-expr-15', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões com Fall: Idioms com fall para erros, envolvimento e declive' },
  { id: 'en-b2-145', language: 'en', level: 'B2', grammarFocus: 'Collocations Avançadas: Combinações Verbais Fortes (firmly believe, utterly fail)' },
  { id: 'en-sup-expr-16', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões sobre Comida (Food): Idioms ingleses com vocabulário gastronômico em sentido figurado' },
  { id: 'en-b2-146', language: 'en', level: 'B2', grammarFocus: 'Phrasal Verbs com Come (Come across, come up with, come down with)' },
  { id: 'en-sup-expr-17', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões sobre Dinheiro (Money): Idioms do inglês para situações financeiras e valorização' },
  { id: 'en-b2-147', language: 'en', level: 'B2', grammarFocus: 'Phrasal Verbs com Put (Put off, put up with, put away)' },
  { id: 'en-sup-expr-18', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões sobre Tempo (Time): Idioms sobre prazo, urgência e rotina em inglês' },
  { id: 'en-b2-148', language: 'en', level: 'B2', grammarFocus: 'Phrasal Verbs com Run (Run out of, run into, run over, run for)' },
  { id: 'en-sup-expr-19', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões sobre Trabalho (Work): Idioms do ambiente profissional e produtividade em inglês' },
  { id: 'en-b2-149', language: 'en', level: 'B2', grammarFocus: 'Inglês Falado: Elisão e Assimilação (wanna, gonna, gimme, kinda)' },
  { id: 'en-sup-expr-20', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões sobre Emoções (Feelings): Idioms para expressões de sentimento e humor em inglês' },
  { id: 'en-b2-150', language: 'en', level: 'B2', grammarFocus: 'Inglês Falado: Omitindo palavras em ambientes informais (Seen John?)' },
  { id: 'en-sup-expr-21', language: 'en', level: 'B2', grammarFocus: 'Expressões e Expressões Idiomáticas: 10 Expressões sobre o Corpo (The Body): Idioms ingleses que usam partes do corpo para significados figurados' },
  { id: 'en-b2-151', language: 'en', level: 'B2', grammarFocus: 'Inglês Britânico vs. Americano — Diferenças de Vocabulário e Ortografia' },
  { id: 'en-b2-152', language: 'en', level: 'B2', grammarFocus: 'Expressões idiomáticas avançadas para conversações naturais: Bite the bullet, Face the music, Burn bridges, Go back to the drawing board, The ball is in your court, Play devil\'s advocate, Turn a blind eye, Push the envelope, Sit on the fence, Cut corners' },

  // ── C1: Advanced ────────────────────────────────────────────────────
  { id: 'en-c1-153', language: 'en', level: 'C1', grammarFocus: 'Inversão com advérbios negativos (Never have I ever..., Hardly had I...)' },
  { id: 'en-c1-154', language: 'en', level: 'C1', grammarFocus: 'Orações Clivadas para ênfase (It was John who... / What I need is...)' },
  { id: 'en-c1-155', language: 'en', level: 'C1', grammarFocus: 'Orações Participiais de raciocínio (Not knowing what to do, she...)' },
  { id: 'en-c1-156', language: 'en', level: 'C1', grammarFocus: 'Orações Participiais de tempo (Having finished my work, I...)' },
  { id: 'en-c1-157', language: 'en', level: 'C1', grammarFocus: 'Condicionais Mistas (Passado afetando o presente / Presente afetando o passado)' },
  { id: 'en-c1-158', language: 'en', level: 'C1', grammarFocus: 'O Subjuntivo em Inglês (I demand that he apologize)' },
  { id: 'en-c1-159', language: 'en', level: 'C1', grammarFocus: 'Marcadores discursivos avançados no inglês falado (As a matter of fact)' },
  { id: 'en-c1-160', language: 'en', level: 'C1', grammarFocus: 'Hedging: Suavizando sua fala (Arguably, presumably, to some extent)' },
  { id: 'en-c1-161', language: 'en', level: 'C1', grammarFocus: 'Substantivos e adjetivos derivados de phrasal verbs (Breakthrough, letdown)' },
  { id: 'en-c1-162', language: 'en', level: 'C1', grammarFocus: 'Comparativos Duplos (The more you study, the better you get)' },
  { id: 'en-c1-163', language: 'en', level: 'C1', grammarFocus: 'Phrasal Verbs Avançados para Negócios e Negociação (Draw up, back down)' },
  { id: 'en-c1-164', language: 'en', level: 'C1', grammarFocus: 'Phrasal verbs com múltiplos significados complexos (Set up, work out)' },
  { id: 'en-c1-165', language: 'en', level: 'C1', grammarFocus: 'Palavras de Ligação com nuances (Nevertheless, furthermore, conversely)' },
  { id: 'en-c1-166', language: 'en', level: 'C1', grammarFocus: 'Collocations Avançadas com preposições (Comply with, derive from, devoid of)' },
  { id: 'en-c1-167', language: 'en', level: 'C1', grammarFocus: 'Idiomatismos: Lidando com situações difíceis (Bite the bullet, face the music)' },
  { id: 'en-c1-168', language: 'en', level: 'C1', grammarFocus: 'Expressões sofisticadas de argumentação e posicionamento em inglês: All things being equal, To a certain extent, It is worth noting that, It stands to reason that, Be that as it may, In this regard, At any rate, It goes without saying, To the best of one\'s ability, Notwithstanding' },

  // ── C2: Mastery ─────────────────────────────────────────────────────
  { id: 'en-c2-169', language: 'en', level: 'C2', grammarFocus: 'Verbos Latinos vs. Phrasal Verbs — Registros Formais vs. Informais (Commence vs. start)' },
  { id: 'en-c2-170', language: 'en', level: 'C2', grammarFocus: 'Pares Binomiais no inglês falado (Sick and tired, loud and clear)' },
  { id: 'en-c2-171', language: 'en', level: 'C2', grammarFocus: 'Sutilezas dos verbos modais (May well, might as well, dare, need, had better)' },
  { id: 'en-c2-172', language: 'en', level: 'C2', grammarFocus: 'Flexibilidade sintática e variedade de sentenças para fala estilizada' },
  { id: 'en-c2-173', language: 'en', level: 'C2', grammarFocus: 'Implicatura conversacional: Lendo nas entrelinhas em inglês' },
  { id: 'en-c2-174', language: 'en', level: 'C2', grammarFocus: 'Dominando o sarcasmo e eufemismo em inglês' },
  { id: 'en-c2-175', language: 'en', level: 'C2', grammarFocus: 'Variações regionais: Diferenças entre inglês falado Americano, Britânico e Australiano' },
  { id: 'en-c2-176', language: 'en', level: 'C2', grammarFocus: 'Gírias e coloquialismos contemporâneos (Lit, vibe, ghosting, flex)' },
  { id: 'en-c2-177', language: 'en', level: 'C2', grammarFocus: 'Idiomatismos Avançados: Expressões de sucesso e fracasso (Go through the roof)' },
  { id: 'en-c2-178', language: 'en', level: 'C2', grammarFocus: 'A linguagem da persuasão, retórica e falar em público' },
  { id: 'en-c2-179', language: 'en', level: 'C2', grammarFocus: 'Fluência Total: Conectando ideias sem traduzir do Português' },
  { id: 'en-c2-180', language: 'en', level: 'C2', grammarFocus: 'Revisão Geral de Todos os Sistemas Gramaticais' },
  { id: 'en-c2-181', language: 'en', level: 'C2', grammarFocus: 'Expressões de alta eloquência e precisão linguística em inglês: The proof of the pudding is in the eating, Between the devil and the deep blue sea, Pyrrhic victory, Hoist by one\'s own petard, Crying wolf, The exception proves the rule, A Gordian knot, Gilding the lily, Damning with faint praise, Passing the Rubicon' },
];
