import type { LessonDefinition, SupportedLanguage } from '@/types';

// ─── French Curriculum (A1–C2) ────────────────────────────────────────────────

export const FRENCH_LESSONS: LessonDefinition[] = [

  // ── A1: Beginner (1–46) ──────────────────────────────────────────────────────
  { id: 'fr-a1-01', language: 'fr', level: 'A1', grammarFocus: 'O alfabeto francês e pronúncia — sons que não existem em português: r gutural, u, eu, nasais' },
  { id: 'fr-a1-02', language: 'fr', level: 'A1', grammarFocus: 'Acentos e cedilha — é, è, ê, ë, ç e como eles mudam a pronúncia' },
  { id: 'fr-a1-03', language: 'fr', level: 'A1', grammarFocus: 'Combinações de letras — ai, ei, an, am, en, em, ou, on, in e seus sons' },
  { id: 'fr-a1-04', language: 'fr', level: 'A1', grammarFocus: 'Letras mudas e liaison — quando letras não se pronunciam e quando se ligam na fala' },
  { id: 'fr-a1-05', language: 'fr', level: 'A1', grammarFocus: 'Cumprimentos e expressões básicas — Bonjour, Merci, Au revoir, S\'il vous plaît, De rien' },
  { id: 'fr-a1-06', language: 'fr', level: 'A1', grammarFocus: 'Apresentar-se — Je m\'appelle..., J\'ai... ans, Je suis..., J\'habite à...' },
  { id: 'fr-a1-07', language: 'fr', level: 'A1', grammarFocus: 'Pronomes pessoais sujeito — je, tu, il/elle, on, nous, vous, ils/elles' },
  { id: 'fr-a1-08', language: 'fr', level: 'A1', grammarFocus: 'Verbo être (ser/estar) no presente — je suis, tu es, il est, nous sommes...' },
  { id: 'fr-a1-09', language: 'fr', level: 'A1', grammarFocus: 'Verbo avoir (ter) no presente — j\'ai, tu as, il a, nous avons...' },
  { id: 'fr-a1-10', language: 'fr', level: 'A1', grammarFocus: 'Artigos definidos — le, la, l\', les (equivalentes a "o, a, os, as")' },
  { id: 'fr-a1-11', language: 'fr', level: 'A1', grammarFocus: 'Artigos indefinidos — un, une, des (equivalentes a "um, uma, uns/umas")' },
  { id: 'fr-a1-12', language: 'fr', level: 'A1', grammarFocus: 'Gênero dos substantivos — regras básicas e terminações comuns para identificar masculino/feminino' },
  { id: 'fr-a1-13', language: 'fr', level: 'A1', grammarFocus: 'Plural dos substantivos — adição de -s e casos irregulares (-aux, -eaux)' },
  { id: 'fr-a1-14', language: 'fr', level: 'A1', grammarFocus: 'Il y a — "há/existe/tem" — expressar a existência de algo: Il y a un chat.' },
  { id: 'fr-a1-15', language: 'fr', level: 'A1', grammarFocus: 'Preposições de lugar — sur, sous, dans, devant, derrière, entre, près de, à côté de' },
  { id: 'fr-a1-16', language: 'fr', level: 'A1', grammarFocus: 'Verbos regulares -ER no presente (singular) — parler, manger, habiter: je parle, tu parles...' },
  { id: 'fr-a1-17', language: 'fr', level: 'A1', grammarFocus: 'Verbos regulares -ER no presente (plural) — nous parlons, vous parlez, ils parlent' },
  { id: 'fr-a1-18', language: 'fr', level: 'A1', grammarFocus: 'Negação básica com être e avoir — je ne suis pas, je n\'ai pas, il n\'est pas' },
  { id: 'fr-a1-19', language: 'fr', level: 'A1', grammarFocus: 'Negação com verbos regulares — je ne parle pas, il ne mange pas, nous ne travaillons pas' },
  { id: 'fr-a1-20', language: 'fr', level: 'A1', grammarFocus: 'Perguntas básicas — entonação ascendente e "est-ce que...": Est-ce que tu parles français?' },
  { id: 'fr-a1-21', language: 'fr', level: 'A1', grammarFocus: 'Palavras interrogativas: Où (onde) e Quand (quando) — Où habites-tu? Quand arrives-tu?' },
  { id: 'fr-a1-22', language: 'fr', level: 'A1', grammarFocus: 'Palavras interrogativas: Comment (como) e Pourquoi (por quê) — Comment tu t\'appelles?' },
  { id: 'fr-a1-23', language: 'fr', level: 'A1', grammarFocus: 'Palavras interrogativas: Qui (quem), Que/Qu\'est-ce que (o quê), Combien (quanto)' },
  { id: 'fr-a1-24', language: 'fr', level: 'A1', grammarFocus: 'Posição dos adjetivos — antes ou depois do substantivo (regra BANGS: Beauty, Age, Number, Goodness, Size)' },
  { id: 'fr-a1-25', language: 'fr', level: 'A1', grammarFocus: 'Concordância dos adjetivos em gênero — grand/grande, petit/petite, beau/belle' },
  { id: 'fr-a1-26', language: 'fr', level: 'A1', grammarFocus: 'Concordância dos adjetivos em número — grands/grandes, petits/petites' },
  { id: 'fr-a1-27', language: 'fr', level: 'A1', grammarFocus: 'As cores — rouge, bleu, vert, jaune, noir, blanc, rose, gris, marron, orange' },
  { id: 'fr-a1-28', language: 'fr', level: 'A1', grammarFocus: 'Adjetivos possessivos (1) — mon/ma/mes, ton/ta/tes, son/sa/ses' },
  { id: 'fr-a1-29', language: 'fr', level: 'A1', grammarFocus: 'Adjetivos possessivos (2) — notre/nos, votre/vos, leur/leurs' },
  { id: 'fr-a1-30', language: 'fr', level: 'A1', grammarFocus: 'Adjetivos demonstrativos — ce, cet, cette, ces (este/essa/esses/essas)' },
  { id: 'fr-a1-31', language: 'fr', level: 'A1', grammarFocus: 'Números de 0 a 100 — zéro, un, dix, vingt, trente, cinquante, cent...' },
  { id: 'fr-a1-32', language: 'fr', level: 'A1', grammarFocus: 'Dias da semana e meses do ano — lundi, mardi, mercredi... / janvier, février...' },
  { id: 'fr-a1-33', language: 'fr', level: 'A1', grammarFocus: 'Dizer as horas — Quelle heure est-il? Il est deux heures et demie / le quart.' },
  { id: 'fr-a1-34', language: 'fr', level: 'A1', grammarFocus: 'Verbo aller (ir) no presente — je vais, tu vas, il va... e o futuro próximo: je vais manger' },
  { id: 'fr-a1-35', language: 'fr', level: 'A1', grammarFocus: 'Preposições com cidades e países — à Paris, en France, au Brésil, aux États-Unis' },
  { id: 'fr-a1-36', language: 'fr', level: 'A1', grammarFocus: 'Artigos contraídos com à — au (à + le), à la, à l\', aux (à + les)' },
  { id: 'fr-a1-37', language: 'fr', level: 'A1', grammarFocus: 'Artigos contraídos com de — du (de + le), de la, de l\', des (de + les)' },
  { id: 'fr-a1-38', language: 'fr', level: 'A1', grammarFocus: 'Verbo faire (fazer) no presente — je fais, tu fais, il fait, nous faisons...' },
  { id: 'fr-a1-39', language: 'fr', level: 'A1', grammarFocus: 'Expressões com avoir — avoir faim, soif, chaud, froid, peur, raison, tort, sommeil' },
  { id: 'fr-a1-40', language: 'fr', level: 'A1', grammarFocus: 'Futuro próximo — aller + infinitif: Je vais manger, Tu vas partir, Elle va dormir' },
  { id: 'fr-a1-41', language: 'fr', level: 'A1', grammarFocus: 'Passado recente — venir de + infinitif: Je viens de manger, Il vient d\'arriver' },
  { id: 'fr-a1-42', language: 'fr', level: 'A1', grammarFocus: 'Conectores básicos — et, mais, ou, alors, donc, parce que (e, mas, ou, então, portanto, porque)' },
  { id: 'fr-a1-43', language: 'fr', level: 'A1', grammarFocus: 'Membros da família — père, mère, frère, sœur, fils, fille, mari, femme, enfants, grands-parents' },
  { id: 'fr-a1-44', language: 'fr', level: 'A1', grammarFocus: 'Clima e estações do ano — Il fait chaud/froid/beau, il pleut, il neige, le printemps, l\'été...' },
  { id: 'fr-a1-45', language: 'fr', level: 'A1', grammarFocus: 'Vocabulário de alimentação — fruits, légumes, viande, boissons e as refeições do dia' },
  { id: 'fr-a1-46', language: 'fr', level: 'A1', grammarFocus: '10 expressões e idiomas essenciais do nível A1' },

  // ── A2: Elementary (47–90) ───────────────────────────────────────────────────
  { id: 'fr-a2-01', language: 'fr', level: 'A2', grammarFocus: 'Verbos regulares -IR no presente — finir, choisir, grandir: je finis, tu finis...' },
  { id: 'fr-a2-02', language: 'fr', level: 'A2', grammarFocus: 'Verbos regulares -RE no presente — répondre, vendre, attendre: je réponds, tu réponds...' },
  { id: 'fr-a2-03', language: 'fr', level: 'A2', grammarFocus: 'Verbo vouloir (querer) no presente — je veux, tu veux, il veut, nous voulons...' },
  { id: 'fr-a2-04', language: 'fr', level: 'A2', grammarFocus: 'Verbo pouvoir (poder) no presente — je peux, tu peux, il peut, nous pouvons...' },
  { id: 'fr-a2-05', language: 'fr', level: 'A2', grammarFocus: 'Verbo devoir (dever/ter que) no presente — je dois, tu dois, il doit, nous devons...' },
  { id: 'fr-a2-06', language: 'fr', level: 'A2', grammarFocus: 'Il faut — expressar obrigação e necessidade: Il faut travailler. Il faut que tu manges.' },
  { id: 'fr-a2-07', language: 'fr', level: 'A2', grammarFocus: 'Artigos partitivos — du, de la, de l\', des (uma parte/quantidade de algo não contável)' },
  { id: 'fr-a2-08', language: 'fr', level: 'A2', grammarFocus: 'Artigos partitivos na negação — pas de/d\': Je ne mange pas de viande.' },
  { id: 'fr-a2-09', language: 'fr', level: 'A2', grammarFocus: 'Verbos pronominais (reflexivos) — se lever, se laver, s\'habiller, s\'appeler (rotina diária)' },
  { id: 'fr-a2-10', language: 'fr', level: 'A2', grammarFocus: 'Pronomes demonstrativos — ce, ça, ceci, cela (isto, isso, aquilo)' },
  { id: 'fr-a2-11', language: 'fr', level: 'A2', grammarFocus: 'Pronomes tônicos — moi, toi, lui, elle, nous, vous, eux, elles (uso após preposições e para ênfase)' },
  { id: 'fr-a2-12', language: 'fr', level: 'A2', grammarFocus: 'Pronomes de objeto direto — le, la, l\', les (o/a/os/as): Je le vois. Elle les mange.' },
  { id: 'fr-a2-13', language: 'fr', level: 'A2', grammarFocus: 'Pronomes de objeto indireto — lui, leur (lhe, lhes): Je lui parle. Elle leur écrit.' },
  { id: 'fr-a2-14', language: 'fr', level: 'A2', grammarFocus: 'Pronomes possessivos — le mien, le tien, le sien, le nôtre, le vôtre, le leur (o meu, o teu...)' },
  { id: 'fr-a2-15', language: 'fr', level: 'A2', grammarFocus: 'Comparativos — plus...que (mais...do que), moins...que (menos...do que), aussi...que (tão...quanto)' },
  { id: 'fr-a2-16', language: 'fr', level: 'A2', grammarFocus: 'Superlativos — le plus... / le moins... (o mais... / o menos...): C\'est le plus beau.' },
  { id: 'fr-a2-17', language: 'fr', level: 'A2', grammarFocus: 'Imperativo — dar ordens e conselhos: Mange! Ne parle pas! Allons-y!' },
  { id: 'fr-a2-18', language: 'fr', level: 'A2', grammarFocus: 'Advérbios de frequência — toujours, souvent, parfois, rarement, jamais (sempre, frequentemente...)' },
  { id: 'fr-a2-19', language: 'fr', level: 'A2', grammarFocus: 'Formação de advérbios em -ment — lentement, rapidement, facilement, heureusement' },
  { id: 'fr-a2-20', language: 'fr', level: 'A2', grammarFocus: 'Advérbios irregulares — bien (bem), mal (mal), mieux (melhor), mieux vs. meilleur' },
  { id: 'fr-a2-21', language: 'fr', level: 'A2', grammarFocus: 'Passé composé com avoir — J\'ai mangé, Tu as vu, Elle a fait, Nous avons parlé' },
  { id: 'fr-a2-22', language: 'fr', level: 'A2', grammarFocus: 'Passé composé com verbos regulares — particípios em -é (parlé), -i (fini), -u (vendu)' },
  { id: 'fr-a2-23', language: 'fr', level: 'A2', grammarFocus: 'Passé composé com particípios irregulares — eu, bu, fait, dit, vu, pris, mis, ouvert' },
  { id: 'fr-a2-24', language: 'fr', level: 'A2', grammarFocus: 'Passé composé com être — Je suis allé(e), Il est arrivé, Elle est née (verbos de movimento)' },
  { id: 'fr-a2-25', language: 'fr', level: 'A2', grammarFocus: 'Passé composé com verbos reflexivos — Elle s\'est levée, Ils se sont parlé' },
  { id: 'fr-a2-26', language: 'fr', level: 'A2', grammarFocus: 'Negação estendida — ne...jamais (nunca), ne...plus (não mais), ne...rien (nada)' },
  { id: 'fr-a2-27', language: 'fr', level: 'A2', grammarFocus: 'Pronome Y — substituindo lugares e expressões com à: J\'y vais. Tu y penses?' },
  { id: 'fr-a2-28', language: 'fr', level: 'A2', grammarFocus: 'Pronome En — substituindo quantidades e expressões com de: J\'en veux. Elle en parle.' },
  { id: 'fr-a2-29', language: 'fr', level: 'A2', grammarFocus: 'Preposições de tempo — pendant (durante), depuis (há/desde), dans (em/daqui a)' },
  { id: 'fr-a2-30', language: 'fr', level: 'A2', grammarFocus: 'Perguntas com inversão — Parles-tu français? Êtes-vous prêt? A-t-il mangé?' },
  { id: 'fr-a2-31', language: 'fr', level: 'A2', grammarFocus: 'Negação restritiva — ne...que (só/apenas): Je ne parle que français. Il n\'a qu\'un euro.' },
  { id: 'fr-a2-32', language: 'fr', level: 'A2', grammarFocus: 'Responder "Si" a perguntas negativas — "Tu ne viens pas?" "Si, je viens!" (equivale a "sim" de contradição)' },
  { id: 'fr-a2-33', language: 'fr', level: 'A2', grammarFocus: 'Connaître vs. Savoir — conhecer pessoas/lugares vs. saber informações/fazer algo' },
  { id: 'fr-a2-34', language: 'fr', level: 'A2', grammarFocus: 'Entendre vs. Écouter / Voir vs. Regarder — ouvir vs. escutar / ver vs. assistir/olhar' },
  { id: 'fr-a2-35', language: 'fr', level: 'A2', grammarFocus: 'Plural dos substantivos em -al, -eau, -ou — cheval→chevaux, gâteau→gâteaux, genou→genoux' },
  { id: 'fr-a2-36', language: 'fr', level: 'A2', grammarFocus: 'Adjetivo interrogativo Quel — Quel livre? Quelle heure? Quels amis? Quelles filles?' },
  { id: 'fr-a2-37', language: 'fr', level: 'A2', grammarFocus: 'Números de 100 a 1.000.000.000 — cent, mille, million, milliard e suas peculiaridades' },
  { id: 'fr-a2-38', language: 'fr', level: 'A2', grammarFocus: 'Números ordinais — 1er, 2ème, 3ème... (primeiro, segundo, terceiro) e seus usos' },
  { id: 'fr-a2-39', language: 'fr', level: 'A2', grammarFocus: 'Vocabulário: esportes e hobbies — les sports et les loisirs' },
  { id: 'fr-a2-40', language: 'fr', level: 'A2', grammarFocus: 'Vocabulário: roupas e moda — les vêtements' },
  { id: 'fr-a2-41', language: 'fr', level: 'A2', grammarFocus: 'Vocabulário: animais — les animaux (domésticos, selvagens e da fazenda)' },
  { id: 'fr-a2-42', language: 'fr', level: 'A2', grammarFocus: 'Vocabulário: profissões — les métiers (médecin, professeur, ingénieur, cuisinier...)' },
  { id: 'fr-a2-43', language: 'fr', level: 'A2', grammarFocus: 'Vocabulário: meios de transporte — les moyens de transport (voiture, train, avion, vélo...)' },
  { id: 'fr-a2-44', language: 'fr', level: 'A2', grammarFocus: '10 expressões e idiomas essenciais do nível A2' },

  // ── B1: Intermediate (91–129) ─────────────────────────────────────────────────
  { id: 'fr-b1-01', language: 'fr', level: 'B1', grammarFocus: 'Imparfait — introdução: formação (-ais, -ais, -ait, -ions, -iez, -aient) e contexto de uso' },
  { id: 'fr-b1-02', language: 'fr', level: 'B1', grammarFocus: 'Imparfait — descrições e hábitos no passado: "Quand j\'étais petit, je jouais souvent..."' },
  { id: 'fr-b1-03', language: 'fr', level: 'B1', grammarFocus: 'Passé composé vs. Imparfait — narrar eventos (PC) vs. descrever o contexto (Imparfait)' },
  { id: 'fr-b1-04', language: 'fr', level: 'B1', grammarFocus: 'Pronome relativo Qui — sujeito da oração relativa: C\'est lui qui parle. La femme qui chante...' },
  { id: 'fr-b1-05', language: 'fr', level: 'B1', grammarFocus: 'Pronome relativo Que/Qu\' — objeto da oração relativa: Le livre que je lis. L\'homme qu\'elle aime.' },
  { id: 'fr-b1-06', language: 'fr', level: 'B1', grammarFocus: 'Pronome relativo Où — indicando lugar e tempo: La ville où j\'habite. Le jour où je suis né.' },
  { id: 'fr-b1-07', language: 'fr', level: 'B1', grammarFocus: 'Pronome relativo Dont — posse e complemento com "de": Le livre dont j\'ai besoin.' },
  { id: 'fr-b1-08', language: 'fr', level: 'B1', grammarFocus: 'Futur simple — verbos regulares: je parlerai, tu finiras, il vendra, nous irons...' },
  { id: 'fr-b1-09', language: 'fr', level: 'B1', grammarFocus: 'Futur simple — radicais irregulares: avoir→aur-, être→ser-, aller→ir-, faire→fer-, vouloir→voudr-' },
  { id: 'fr-b1-10', language: 'fr', level: 'B1', grammarFocus: 'Orações temporais com Quand/Lorsque + futur — Quand tu arriveras, je serai là.' },
  { id: 'fr-b1-11', language: 'fr', level: 'B1', grammarFocus: 'Conditionnel présent — pedidos educados e situações imaginárias: Je voudrais, Tu pourrais...' },
  { id: 'fr-b1-12', language: 'fr', level: 'B1', grammarFocus: '1ª condicional (hipótese real) — Si + présent → futur: Si tu viens, je serai content.' },
  { id: 'fr-b1-13', language: 'fr', level: 'B1', grammarFocus: '2ª condicional (hipótese irreal) — Si + imparfait → conditionnel: Si j\'avais de l\'argent...' },
  { id: 'fr-b1-14', language: 'fr', level: 'B1', grammarFocus: 'Posição dos pronomes em frases negativas — Je ne le vois pas. Elle ne lui parle plus.' },
  { id: 'fr-b1-15', language: 'fr', level: 'B1', grammarFocus: 'Pronomes de objeto duplo — me le, te la, lui en, nous les... e a ordem correta' },
  { id: 'fr-b1-16', language: 'fr', level: 'B1', grammarFocus: 'Concordância do particípio passado com objeto direto precedente — Je les ai vus. Elle l\'a mangée.' },
  { id: 'fr-b1-17', language: 'fr', level: 'B1', grammarFocus: 'Artigos partitivos avançados — generalizações sem artigo vs. quantidades com du/de la/des' },
  { id: 'fr-b1-18', language: 'fr', level: 'B1', grammarFocus: 'Adjetivos indefinidos — chaque (cada), certain (certo), plusieurs (vários), quelque (algum)' },
  { id: 'fr-b1-19', language: 'fr', level: 'B1', grammarFocus: 'Adjetivos que mudam de sentido antes/depois do substantivo — ancien, propre, même, dernier, pauvre' },
  { id: 'fr-b1-20', language: 'fr', level: 'B1', grammarFocus: 'Concordância de cores compostas — bleu clair, vert foncé (invariáveis quando modificadas)' },
  { id: 'fr-b1-21', language: 'fr', level: 'B1', grammarFocus: 'Pronomes demonstrativos — celui, celle, ceux, celles + ci/là: celui-ci vs. celui-là' },
  { id: 'fr-b1-22', language: 'fr', level: 'B1', grammarFocus: 'Gerúndio (gérondif) — en + participe présent para ações simultâneas: en mangeant, en parlant' },
  { id: 'fr-b1-23', language: 'fr', level: 'B1', grammarFocus: 'Estruturas com infinitivo — avant de, au lieu de, sans + infinitif: avant de partir, sans savoir' },
  { id: 'fr-b1-24', language: 'fr', level: 'B1', grammarFocus: 'Pronomes relativos compostos — lequel, laquelle, lesquels, lesquelles (após preposições)' },
  { id: 'fr-b1-25', language: 'fr', level: 'B1', grammarFocus: 'Voz passiva (presente e passado) — être + participe passé: Le livre est lu. Le gâteau a été mangé.' },
  { id: 'fr-b1-26', language: 'fr', level: 'B1', grammarFocus: 'Conjunções coordenativas — mais, ou, et, donc, or, ni, car (mas, ou, e, portanto, ora, nem, pois)' },
  { id: 'fr-b1-27', language: 'fr', level: 'B1', grammarFocus: 'Conjunções subordinativas — parce que, quand, si, comme, bien que, puisque, bien que + subj.' },
  { id: 'fr-b1-28', language: 'fr', level: 'B1', grammarFocus: 'Conjunções temporais — dès que, aussitôt que, avant que + subj., après que + indic.' },
  { id: 'fr-b1-29', language: 'fr', level: 'B1', grammarFocus: 'Discurso relatado no presente — Il dit que..., Elle pense que..., Ils annoncent que...' },
  { id: 'fr-b1-30', language: 'fr', level: 'B1', grammarFocus: 'Preposições compostas — à cause de, grâce à, au lieu de, à côté de, en face de, au bout de' },
  { id: 'fr-b1-31', language: 'fr', level: 'B1', grammarFocus: 'Verbos seguidos de "à" ou "de" + infinitif — aider à, commencer à, essayer de, décider de' },
  { id: 'fr-b1-32', language: 'fr', level: 'B1', grammarFocus: 'Pronomes indefinidos — quelqu\'un, quelque chose, personne, rien, tout, chacun, n\'importe qui' },
  { id: 'fr-b1-33', language: 'fr', level: 'B1', grammarFocus: 'Verbos impessoais — falloir, pleuvoir, neiger, valoir, s\'agir de, être question de...' },
  { id: 'fr-b1-34', language: 'fr', level: 'B1', grammarFocus: 'Uso de Tout — tout/toute/tous/toutes como adjetivo, pronome e advérbio (tudo, todos, completamente)' },
  { id: 'fr-b1-35', language: 'fr', level: 'B1', grammarFocus: 'Pronomes tônicos com Même — moi-même, toi-même, lui-même (eu mesmo, tu mesmo, ele mesmo)' },
  { id: 'fr-b1-36', language: 'fr', level: 'B1', grammarFocus: 'Nominalização — transformar verbos/adjetivos em substantivos: arriver → l\'arrivée, décider → la décision' },
  { id: 'fr-b1-37', language: 'fr', level: 'B1', grammarFocus: 'Falsos cognatos francês-português (les faux amis) — actually, prétendre, sensible, réaliser...' },
  { id: 'fr-b1-38', language: 'fr', level: 'B1', grammarFocus: 'Orações independentes, principais e subordinadas — estrutura da frase complexa em francês' },
  { id: 'fr-b1-39', language: 'fr', level: 'B1', grammarFocus: '10 expressões e idiomas essenciais do nível B1' },

  // ── B2: Upper-Intermediate (130–168) ──────────────────────────────────────────
  { id: 'fr-b2-01', language: 'fr', level: 'B2', grammarFocus: 'Subjonctif présent — formação e conjugação: que je parle, que tu finisses, qu\'il aille' },
  { id: 'fr-b2-02', language: 'fr', level: 'B2', grammarFocus: 'Subjonctif para necessidade — Il faut que..., Il est nécessaire que..., Il est important que...' },
  { id: 'fr-b2-03', language: 'fr', level: 'B2', grammarFocus: 'Subjonctif para desejos e reações emocionais — Je veux que, J\'aime que, Je suis content que' },
  { id: 'fr-b2-04', language: 'fr', level: 'B2', grammarFocus: 'Subjonctif para dúvida e incerteza — Je doute que, Il est possible que, Je ne crois pas que' },
  { id: 'fr-b2-05', language: 'fr', level: 'B2', grammarFocus: 'Orações concessivas com subjonctif — bien que, quoique + subjonctif: Bien qu\'il soit fatigué...' },
  { id: 'fr-b2-06', language: 'fr', level: 'B2', grammarFocus: 'Orações de finalidade com subjonctif — pour que, afin que: Je parle lentement pour qu\'il comprenne.' },
  { id: 'fr-b2-07', language: 'fr', level: 'B2', grammarFocus: 'Conjunções negativas — sans que, à moins que + subjonctif' },
  { id: 'fr-b2-08', language: 'fr', level: 'B2', grammarFocus: 'Verbos de opinião: indicatif vs. subjonctif — croire que + indicatif vs. ne pas croire que + subj.' },
  { id: 'fr-b2-09', language: 'fr', level: 'B2', grammarFocus: 'Plus-que-parfait — ação anterior a outra no passado: J\'avais mangé quand il est arrivé.' },
  { id: 'fr-b2-10', language: 'fr', level: 'B2', grammarFocus: 'Conditionnel passé e 3ª condicional — Si + PQP → conditionnel passé: Si j\'avais su, j\'aurais agi.' },
  { id: 'fr-b2-11', language: 'fr', level: 'B2', grammarFocus: 'Futur antérieur — ação que estará concluída no futuro: Quand tu arriveras, j\'aurai fini.' },
  { id: 'fr-b2-12', language: 'fr', level: 'B2', grammarFocus: 'Discurso relatado no passado — concordância dos tempos verbais em francês' },
  { id: 'fr-b2-13', language: 'fr', level: 'B2', grammarFocus: 'Construção causativa com faire — faire + infinitif: Je fais réparer la voiture. Il fait rire tout le monde.' },
  { id: 'fr-b2-14', language: 'fr', level: 'B2', grammarFocus: 'Causativa avançada com se faire — se faire + infinitif: Elle s\'est fait couper les cheveux.' },
  { id: 'fr-b2-15', language: 'fr', level: 'B2', grammarFocus: 'Causativa avançada com se laisser — se laisser + infinitif: Il s\'est laissé convaincre.' },
  { id: 'fr-b2-16', language: 'fr', level: 'B2', grammarFocus: 'Ordem dupla de pronomes no imperativo — Donne-le-moi! Ne me le donne pas!' },
  { id: 'fr-b2-17', language: 'fr', level: 'B2', grammarFocus: 'Expressar necessidade avançada — avoir besoin de vs. falloir: J\'ai besoin d\'aide vs. Il faut de l\'aide.' },
  { id: 'fr-b2-18', language: 'fr', level: 'B2', grammarFocus: 'Infinitivo passado — après avoir/être + participe passé: Après avoir mangé, il est parti.' },
  { id: 'fr-b2-19', language: 'fr', level: 'B2', grammarFocus: 'Ne explétif — uso do "ne" sem valor negativo: J\'ai peur qu\'il ne vienne. avant qu\'il ne parte.' },
  { id: 'fr-b2-20', language: 'fr', level: 'B2', grammarFocus: 'Revisão: verbos de opinião com indicatif vs. subjonctif (extensão e casos ambíguos)' },
  { id: 'fr-b2-21', language: 'fr', level: 'B2', grammarFocus: 'Pronome relativo auquel — contração de à + lequel: Le projet auquel je participe.' },
  { id: 'fr-b2-22', language: 'fr', level: 'B2', grammarFocus: 'Pronome relativo duquel — contração de de + lequel: Le problème duquel il parle.' },
  { id: 'fr-b2-23', language: 'fr', level: 'B2', grammarFocus: 'Prefixos — formação de palavras: dé-, re-, in-, im-, pré-, sur-, sous-, anti-, co-...' },
  { id: 'fr-b2-24', language: 'fr', level: 'B2', grammarFocus: 'Sufixos — formação de palavras: -tion, -ment, -eur/-euse, -iste, -able/-ible, -ité...' },
  { id: 'fr-b2-25', language: 'fr', level: 'B2', grammarFocus: 'Plurais irregulares — revisão completa: -al→-aux, -ail→-aux, -eu→-eux e exceções' },
  { id: 'fr-b2-26', language: 'fr', level: 'B2', grammarFocus: 'Marcadores de discurso — tout d\'abord, ensuite, de plus, en revanche, néanmoins, par conséquent' },
  { id: 'fr-b2-27', language: 'fr', level: 'B2', grammarFocus: 'C\'est vs. Il est — usos e diferenças: C\'est un médecin. Il est médecin. C\'est beau. Il est beau.' },
  { id: 'fr-b2-28', language: 'fr', level: 'B2', grammarFocus: 'On vs. L\'on — variação estilística: On dit... / L\'on dit... (uso formal e literário)' },
  { id: 'fr-b2-29', language: 'fr', level: 'B2', grammarFocus: 'Verbos com S\'en — s\'en aller, s\'en sortir, s\'en vouloir, s\'en prendre à, s\'en moquer' },
  { id: 'fr-b2-30', language: 'fr', level: 'B2', grammarFocus: 'Pontuação em francês — guillemets «», tirets —, points de suspension…, deux-points :' },
  { id: 'fr-b2-31', language: 'fr', level: 'B2', grammarFocus: 'Superlativos complexos — le plus grand que j\'aie vu (subjonctif) e outras estruturas avançadas' },
  { id: 'fr-b2-32', language: 'fr', level: 'B2', grammarFocus: 'Passé simple — reconhecimento de verbos regulares em textos literários: il parla, elle finit, ils vendirent' },
  { id: 'fr-b2-33', language: 'fr', level: 'B2', grammarFocus: 'Passé simple — reconhecimento de verbos irregulares: fut, eut, alla, fit, vit, prit, dit' },
  { id: 'fr-b2-34', language: 'fr', level: 'B2', grammarFocus: 'Particípio presente vs. adjetivo verbal — en chantant (ação) vs. une femme charmante (qualidade)' },
  { id: 'fr-b2-35', language: 'fr', level: 'B2', grammarFocus: 'Pronomes demonstrativos indefinidos avançados — ceci, cela, ça, ceux-ci, ceux-là (usos e nuances)' },
  { id: 'fr-b2-36', language: 'fr', level: 'B2', grammarFocus: 'Números, frações e unidades de medida — usage avançado: un tiers, trois quarts, un litre de...' },
  { id: 'fr-b2-37', language: 'fr', level: 'B2', grammarFocus: 'Revisão: todos os pronomes relativos — qui, que, où, dont, lequel, auquel, duquel, ce qui, ce que, ce dont' },
  { id: 'fr-b2-38', language: 'fr', level: 'B2', grammarFocus: 'Revisão: todos os artigos — definido, indefinido e partitivo (comparação completa e casos especiais)' },
  { id: 'fr-b2-39', language: 'fr', level: 'B2', grammarFocus: '10 expressões e idiomas essenciais do nível B2' },

  // ── C1: Advanced (169–185) ────────────────────────────────────────────────────
  { id: 'fr-c1-01', language: 'fr', level: 'C1', grammarFocus: 'Inversão estilística — perguntas e ênfase em francês formal: Peut-être est-il venu. Ainsi parla...' },
  { id: 'fr-c1-02', language: 'fr', level: 'C1', grammarFocus: 'Frases clivadas — c\'est...qui, c\'est...que, ce dont: C\'est lui qui a gagné. Ce dont j\'ai besoin...' },
  { id: 'fr-c1-03', language: 'fr', level: 'C1', grammarFocus: 'Entonação vs. inversão em discurso formal e escrito — quando e como usar cada estrutura' },
  { id: 'fr-c1-04', language: 'fr', level: 'C1', grammarFocus: 'Construções causais avançadas — parce que, puisque, vu que, étant donné que, du fait que, dès lors que' },
  { id: 'fr-c1-05', language: 'fr', level: 'C1', grammarFocus: 'Concessivas avançadas — malgré, en dépit de, encore que, quitte à, avoir beau + infinitif' },
  { id: 'fr-c1-06', language: 'fr', level: 'C1', grammarFocus: 'Preposições estilísticas e formações adverbiais elaboradas no francês formal e literário' },
  { id: 'fr-c1-07', language: 'fr', level: 'C1', grammarFocus: 'Subjonctif passé — formação e uso: Je suis content qu\'il soit venu. Bien qu\'elle ait réussi...' },
  { id: 'fr-c1-08', language: 'fr', level: 'C1', grammarFocus: 'Usos avançados do subjonctif com ne explétif — avant qu\'il ne parte, à moins qu\'il ne vienne' },
  { id: 'fr-c1-09', language: 'fr', level: 'C1', grammarFocus: 'Passé antérieur — reconhecimento em literatura: Quand il eut parlé, elle se leva.' },
  { id: 'fr-c1-10', language: 'fr', level: 'C1', grammarFocus: 'Formas verbais arcaicas encontradas em literatura clássica francesa — passé simple, subjonctif imparfait' },
  { id: 'fr-c1-11', language: 'fr', level: 'C1', grammarFocus: 'Nuances de estrutura — omissão do artigo, escolhas entre construções e seu efeito de sentido' },
  { id: 'fr-c1-12', language: 'fr', level: 'C1', grammarFocus: 'Marcadores de discurso para argumentação — en effet, certes, or, qui plus est, c\'est pourquoi, d\'autant plus que' },
  { id: 'fr-c1-13', language: 'fr', level: 'C1', grammarFocus: 'Apócope e truncação no francês falado — le ciné, la fac, un frigo, la météo, le resto, un appart' },
  { id: 'fr-c1-14', language: 'fr', level: 'C1', grammarFocus: 'Verbos pronominais avançados — usos recíprocos (ils se parlent), passivos (ça se dit) e idiomáticos' },
  { id: 'fr-c1-15', language: 'fr', level: 'C1', grammarFocus: 'Contrastes de registro: negação e perguntas — ne...pas vs. pas seul / inversion vs. est-ce que' },
  { id: 'fr-c1-16', language: 'fr', level: 'C1', grammarFocus: 'Expressões avançadas de causa, consequência e oposição — d\'où, si bien que, alors que, tandis que' },
  { id: 'fr-c1-17', language: 'fr', level: 'C1', grammarFocus: '10 expressões e idiomas essenciais do nível C1' },

  // ── C2: Mastery (186–200) ─────────────────────────────────────────────────────
  { id: 'fr-c2-01', language: 'fr', level: 'C2', grammarFocus: 'Imparfait du subjonctif — reconhecimento e uso literário: Il fallait qu\'il parlât. Bien qu\'elle fût...' },
  { id: 'fr-c2-02', language: 'fr', level: 'C2', grammarFocus: 'Plus-que-parfait du subjonctif — literatura formal: Il eût fallu qu\'elle fût venue plus tôt.' },
  { id: 'fr-c2-03', language: 'fr', level: 'C2', grammarFocus: 'Seconde forme du conditionnel passé — Il eût aimé savoir. (equivalente ao conditionnel passé em contexto literário)' },
  { id: 'fr-c2-04', language: 'fr', level: 'C2', grammarFocus: 'Registro formal (soutenu) vs. padrão falado (courant) — diferenças sistemáticas e escolhas de vocabulário' },
  { id: 'fr-c2-05', language: 'fr', level: 'C2', grammarFocus: 'Registro informal (familier) e gíria — argot, verlan (l\'envers), expressões do francês contemporâneo' },
  { id: 'fr-c2-06', language: 'fr', level: 'C2', grammarFocus: 'Formas literárias de negação — ne...point, ne...guère, nul ne, aucun ne + nuances de sentido' },
  { id: 'fr-c2-07', language: 'fr', level: 'C2', grammarFocus: 'Reescrita estrutural complexa — transformar frases para aprimoramento estilístico e clareza' },
  { id: 'fr-c2-08', language: 'fr', level: 'C2', grammarFocus: 'A arte da argumentação em francês — conectar, contrastar e desenvolver ideias no nível C2' },
  { id: 'fr-c2-09', language: 'fr', level: 'C2', grammarFocus: 'Elipse e redução sintática no francês literário — supressão de elementos e compactação da frase' },
  { id: 'fr-c2-10', language: 'fr', level: 'C2', grammarFocus: 'Escolhas estilísticas — ativo vs. passivo, nominalização vs. verbo, inversão vs. ordem direta' },
  { id: 'fr-c2-11', language: 'fr', level: 'C2', grammarFocus: 'Decodificar textos autênticos complexos — literário, jornalístico e jurídico em francês' },
  { id: 'fr-c2-12', language: 'fr', level: 'C2', grammarFocus: 'Combinação avançada de registros — quando e como alternar entre formal, padrão e informal' },
  { id: 'fr-c2-13', language: 'fr', level: 'C2', grammarFocus: 'Domínio de estruturas idiomáticas do francês — expressões cristalizadas, coloquialismos e provérbios' },
  { id: 'fr-c2-14', language: 'fr', level: 'C2', grammarFocus: 'Revisão de todos os sistemas gramaticais — do A1 ao C2: síntese e consolidação' },
  { id: 'fr-c2-15', language: 'fr', level: 'C2', grammarFocus: '10 expressões e idiomas essenciais do nível C2' },
];

// ─── English Curriculum (A1–C2) ───────────────────────────────────────────────

export const ENGLISH_LESSONS: LessonDefinition[] = [

  // ── A1: Beginner (1–37) ───────────────────────────────────────────────────────
  { id: 'en-a1-01', language: 'en', level: 'A1', grammarFocus: 'Sons do inglês e o alfabeto — sons que não existem em português: TH, V/B, vogais longas/curtas' },
  { id: 'en-a1-02', language: 'en', level: 'A1', grammarFocus: 'Tonicidade e ritmo — como acentuar palavras e frases em inglês (word stress e sentence stress)' },
  { id: 'en-a1-03', language: 'en', level: 'A1', grammarFocus: 'Pronomes pessoais sujeito — I, you, he, she, it, we, they (eu, você, ele, ela, nós, eles)' },
  { id: 'en-a1-04', language: 'en', level: 'A1', grammarFocus: 'Verbo "to be" no presente (afirmativo) — I am, you are, he/she/it is, we are, they are' },
  { id: 'en-a1-05', language: 'en', level: 'A1', grammarFocus: 'Verbo "to be" (negativo e interrogativo) — I\'m not, Are you...? Is she...? They aren\'t...' },
  { id: 'en-a1-06', language: 'en', level: 'A1', grammarFocus: 'Artigos definidos e indefinidos — A, An, The (regras de uso e diferença do português)' },
  { id: 'en-a1-07', language: 'en', level: 'A1', grammarFocus: 'Pronomes demonstrativos — This, That, These, Those (este, esse/aquele, estes, esses/aqueles)' },
  { id: 'en-a1-08', language: 'en', level: 'A1', grammarFocus: 'Plural dos substantivos — regras com -s/-es e irregulares: men, women, children, feet, teeth' },
  { id: 'en-a1-09', language: 'en', level: 'A1', grammarFocus: 'Adjetivos possessivos — My, your, his, her, its, our, their (meu, seu, dele, dela, nosso, deles)' },
  { id: 'en-a1-10', language: 'en', level: 'A1', grammarFocus: 'Caso possessivo \'S — John\'s car (o carro do João) vs. The car of John' },
  { id: 'en-a1-11', language: 'en', level: 'A1', grammarFocus: 'Números de 0 a 100 — zero, one, ten, twenty, fifty, one hundred e pronúncia' },
  { id: 'en-a1-12', language: 'en', level: 'A1', grammarFocus: 'Presente simples com I, You, We, They — hábitos e rotinas: I work, we eat, they live' },
  { id: 'en-a1-13', language: 'en', level: 'A1', grammarFocus: 'Presente simples com He, She, It — adição de -s/-es: she works, he watches, it goes' },
  { id: 'en-a1-14', language: 'en', level: 'A1', grammarFocus: 'Negativa e perguntas no presente simples — Do/Does: I don\'t, Does she...? They don\'t...' },
  { id: 'en-a1-15', language: 'en', level: 'A1', grammarFocus: 'Advérbios de frequência — always, usually, often, sometimes, rarely, never e posição na frase' },
  { id: 'en-a1-16', language: 'en', level: 'A1', grammarFocus: 'Palavras interrogativas: What (o quê), Who (quem), Where (onde) — formação de perguntas' },
  { id: 'en-a1-17', language: 'en', level: 'A1', grammarFocus: 'Palavras interrogativas: When (quando), Why (por quê), How (como) — formação de perguntas' },
  { id: 'en-a1-18', language: 'en', level: 'A1', grammarFocus: 'There is / There are — expressar existência e localização: There is a cat. There are two books.' },
  { id: 'en-a1-19', language: 'en', level: 'A1', grammarFocus: 'Preposições de lugar — In, On, At (em/no/na): in the box, on the table, at the door' },
  { id: 'en-a1-20', language: 'en', level: 'A1', grammarFocus: 'Preposições de tempo — In (meses/anos), On (dias/datas), At (horas): in June, on Monday, at 5pm' },
  { id: 'en-a1-21', language: 'en', level: 'A1', grammarFocus: 'Modal "Can/Can\'t" — habilidade e permissão: I can swim. She can\'t drive. Can I help you?' },
  { id: 'en-a1-22', language: 'en', level: 'A1', grammarFocus: 'Presente contínuo — I am eating, She is working, They are playing (ação acontecendo agora)' },
  { id: 'en-a1-23', language: 'en', level: 'A1', grammarFocus: 'Presente contínuo vs. Presente simples — I am eating (agora) vs. I eat (sempre/hábito)' },
  { id: 'en-a1-24', language: 'en', level: 'A1', grammarFocus: 'Dias da semana e meses do ano — Monday, Tuesday... / January, February... e pronúncia' },
  { id: 'en-a1-25', language: 'en', level: 'A1', grammarFocus: 'Dizer as horas — It\'s half past two, It\'s quarter to five, It\'s ten past three' },
  { id: 'en-a1-26', language: 'en', level: 'A1', grammarFocus: 'Vocabulário de rotina diária e colocações — take a shower, have breakfast, go to bed, get up' },
  { id: 'en-a1-27', language: 'en', level: 'A1', grammarFocus: 'Verbo "to have" — posse e refeições: have a car, have lunch, have fun, have a shower' },
  { id: 'en-a1-28', language: 'en', level: 'A1', grammarFocus: 'Adjetivos comuns e seus opostos — big/small, hot/cold, young/old, happy/sad, fast/slow' },
  { id: 'en-a1-29', language: 'en', level: 'A1', grammarFocus: 'Cores, formas e descrições básicas — red, blue, round, square, tall, short, long, dark' },
  { id: 'en-a1-30', language: 'en', level: 'A1', grammarFocus: 'Membros da família e relacionamentos — father, mother, brother, sister, husband, wife, cousin' },
  { id: 'en-a1-31', language: 'en', level: 'A1', grammarFocus: 'Pronomes objeto — Me, him, her, us, them: She loves him. I see them. Can you help me?' },
  { id: 'en-a1-32', language: 'en', level: 'A1', grammarFocus: 'Substantivos contáveis e plurais — a book / two books / some books / many books' },
  { id: 'en-a1-33', language: 'en', level: 'A1', grammarFocus: 'Substantivos incontáveis — water, information, bread, money, furniture (sem plural)' },
  { id: 'en-a1-34', language: 'en', level: 'A1', grammarFocus: 'Quantificadores: Some vs. Any — afirmativo (some) vs. negativo/interrogativo (any)' },
  { id: 'en-a1-35', language: 'en', level: 'A1', grammarFocus: 'How much vs. How many — incontáveis: How much water? / contáveis: How many books?' },
  { id: 'en-a1-36', language: 'en', level: 'A1', grammarFocus: 'Phrasal verbs básicos — wake up, stand up, sit down, turn on, turn off, pick up, put down' },
  { id: 'en-a1-37', language: 'en', level: 'A1', grammarFocus: '10 expressões e idiomas essenciais do nível A1' },

  // ── A2: Elementary (38–78) ────────────────────────────────────────────────────
  { id: 'en-a2-01', language: 'en', level: 'A2', grammarFocus: 'Verbo "to be" no passado — Was/Were: I was tired, you were right, she wasn\'t there' },
  { id: 'en-a2-02', language: 'en', level: 'A2', grammarFocus: 'Passado simples com verbos regulares — worked, played, visited (pronúncia: /t/ /d/ /id/)' },
  { id: 'en-a2-03', language: 'en', level: 'A2', grammarFocus: 'Passado simples — verbos irregulares parte 1: go/went, do/did, have/had, make/made, come/came' },
  { id: 'en-a2-04', language: 'en', level: 'A2', grammarFocus: 'Passado simples — verbos irregulares parte 2: say/said, see/saw, get/got, take/took, know/knew' },
  { id: 'en-a2-05', language: 'en', level: 'A2', grammarFocus: 'Negativa e perguntas no passado simples — Did/Didn\'t: I didn\'t go. Did you see her?' },
  { id: 'en-a2-06', language: 'en', level: 'A2', grammarFocus: 'Adjetivos comparativos — taller than, more expensive than, better than, worse than' },
  { id: 'en-a2-07', language: 'en', level: 'A2', grammarFocus: 'Adjetivos superlativos — the tallest, the most expensive, the best, the worst' },
  { id: 'en-a2-08', language: 'en', level: 'A2', grammarFocus: 'Estrutura As...as — igualdade: as tall as, as good as, not as fast as' },
  { id: 'en-a2-09', language: 'en', level: 'A2', grammarFocus: 'Futuro com Going To — planos e intenções: I\'m going to travel. She\'s going to study.' },
  { id: 'en-a2-10', language: 'en', level: 'A2', grammarFocus: 'Futuro com Will — previsões e promessas espontâneas: It will rain. I\'ll help you!' },
  { id: 'en-a2-11', language: 'en', level: 'A2', grammarFocus: 'Will vs. Going To — decisão espontânea (will) vs. plano concreto (going to)' },
  { id: 'en-a2-12', language: 'en', level: 'A2', grammarFocus: 'Modal Should/Shouldn\'t — dar conselhos: You should rest. You shouldn\'t eat so much.' },
  { id: 'en-a2-13', language: 'en', level: 'A2', grammarFocus: 'Obrigação — Have to vs. Must: I have to work (regra externa) vs. You must stop (obrigação pessoal)' },
  { id: 'en-a2-14', language: 'en', level: 'A2', grammarFocus: 'Ausência de obrigação — Don\'t have to vs. Mustn\'t: You don\'t have to come (opcional) vs. não pode' },
  { id: 'en-a2-15', language: 'en', level: 'A2', grammarFocus: 'Would like to — pedidos educados: I\'d like a coffee, please. Would you like some tea?' },
  { id: 'en-a2-16', language: 'en', level: 'A2', grammarFocus: 'Pronomes compostos: Something, Anything, Nothing, Everything — em contextos afirmativos e negativos' },
  { id: 'en-a2-17', language: 'en', level: 'A2', grammarFocus: 'Pronomes compostos: Someone, Anyone, No one, Everyone — pessoas em contextos variados' },
  { id: 'en-a2-18', language: 'en', level: 'A2', grammarFocus: 'Conjunções: And, but, so, because — conectar ideias e justificar ações' },
  { id: 'en-a2-19', language: 'en', level: 'A2', grammarFocus: 'Advérbios de modo com -ly — slowly, quickly, carefully, loudly, quietly, happily' },
  { id: 'en-a2-20', language: 'en', level: 'A2', grammarFocus: 'Modificadores de advérbio — very, really, quite, too, so, a bit, extremely' },
  { id: 'en-a2-21', language: 'en', level: 'A2', grammarFocus: 'Colocações com Make vs. Do (parte 1) — make a mistake, make a decision, do homework, do a course' },
  { id: 'en-a2-22', language: 'en', level: 'A2', grammarFocus: 'Phrasal verbs com Look — look at, look for, look after, look up, look forward to' },
  { id: 'en-a2-23', language: 'en', level: 'A2', grammarFocus: 'Phrasal verbs de deslocamento — get in, get out, get on, get off, get into, get out of' },
  { id: 'en-a2-24', language: 'en', level: 'A2', grammarFocus: 'Expressões de quantidade — a lot of, many, much, a few, a little, plenty of, enough' },
  { id: 'en-a2-25', language: 'en', level: 'A2', grammarFocus: 'Exclamações — What a...! (Que...!): What a great idea! / How...! (Como...!): How beautiful!' },
  { id: 'en-a2-26', language: 'en', level: 'A2', grammarFocus: 'Vocabulário: clima e estações do ano — sunny, cloudy, rainy, windy, spring, summer...' },
  { id: 'en-a2-27', language: 'en', level: 'A2', grammarFocus: 'Dar e pedir direções — Turn left, go straight ahead, it\'s on the corner, next to, opposite' },
  { id: 'en-a2-28', language: 'en', level: 'A2', grammarFocus: 'Verbo + Infinitivo — want to, hope to, need to, decide to, plan to, agree to, refuse to' },
  { id: 'en-a2-29', language: 'en', level: 'A2', grammarFocus: 'Verbo + Gerúndio — enjoy reading, finish eating, avoid going, keep trying, mind waiting' },
  { id: 'en-a2-30', language: 'en', level: 'A2', grammarFocus: 'Infinitivo de propósito — I went to the store TO buy milk. She called TO invite him.' },
  { id: 'en-a2-31', language: 'en', level: 'A2', grammarFocus: 'Imperativo — dar instruções, avisos e pedidos: Open the door! Don\'t touch! Please sit down.' },
  { id: 'en-a2-32', language: 'en', level: 'A2', grammarFocus: 'Presente contínuo para o futuro — planos marcados: I\'m meeting her tonight. We\'re flying tomorrow.' },
  { id: 'en-a2-33', language: 'en', level: 'A2', grammarFocus: 'Expressões de preenchimento — Well, you know, like, actually, I mean, kind of, sort of' },
  { id: 'en-a2-34', language: 'en', level: 'A2', grammarFocus: 'Idiomas para emoções — over the moon (muito feliz), feeling blue (triste), over the top (exagerado)' },
  { id: 'en-a2-35', language: 'en', level: 'A2', grammarFocus: 'Respostas naturais em conversas — Me too, Me neither, So do I, Neither do I, I hope so' },
  { id: 'en-a2-36', language: 'en', level: 'A2', grammarFocus: 'Números 101+ e números ordinais — first, second, third, hundredth, thousandth e usos' },
  { id: 'en-a2-37', language: 'en', level: 'A2', grammarFocus: 'Vocabulário: profissões e o ambiente de trabalho — doctor, teacher, engineer, office, boss' },
  { id: 'en-a2-38', language: 'en', level: 'A2', grammarFocus: 'Vocabulário: partes do corpo e saúde — head, arm, stomach, headache, fever, appointment' },
  { id: 'en-a2-39', language: 'en', level: 'A2', grammarFocus: 'Vocabulário: esportes e hobbies — play football, go swimming, do yoga, photography, cooking' },
  { id: 'en-a2-40', language: 'en', level: 'A2', grammarFocus: 'Falsos cognatos inglês-português — actually (na verdade), eventually (finalmente), pretend (fingir), sensible (sensato)' },
  { id: 'en-a2-41', language: 'en', level: 'A2', grammarFocus: '10 expressões e idiomas essenciais do nível A2' },

  // ── B1: Intermediate (79–114) ─────────────────────────────────────────────────
  { id: 'en-b1-01', language: 'en', level: 'B1', grammarFocus: 'Introdução ao Present Perfect — Have/Has + Past Participle: I have eaten, She has gone' },
  { id: 'en-b1-02', language: 'en', level: 'B1', grammarFocus: 'Present Perfect — experiências de vida: Have you ever been to Paris? I\'ve never tried sushi.' },
  { id: 'en-b1-03', language: 'en', level: 'B1', grammarFocus: 'Present Perfect vs. Simple Past — passado não concluído/relevante vs. passado concluído' },
  { id: 'en-b1-04', language: 'en', level: 'B1', grammarFocus: 'Present Perfect com Just, Already, Yet — I\'ve just arrived. Have you finished yet? I\'ve already eaten.' },
  { id: 'en-b1-05', language: 'en', level: 'B1', grammarFocus: 'Present Perfect com For e Since — I\'ve lived here for 5 years / since 2019.' },
  { id: 'en-b1-06', language: 'en', level: 'B1', grammarFocus: 'Colocações: adjetivos + preposições — good at, afraid of, proud of, interested in, tired of' },
  { id: 'en-b1-07', language: 'en', level: 'B1', grammarFocus: 'Colocações: verbos + preposições — depend on, apologize for, believe in, apply for, agree with' },
  { id: 'en-b1-08', language: 'en', level: 'B1', grammarFocus: 'Colocações com Make vs. Do (parte 2) — make a difference, make progress, do your best, do a favour' },
  { id: 'en-b1-09', language: 'en', level: 'B1', grammarFocus: '1ª condicional — If + Present + Will: If it rains, I will stay home. (hipóteses reais)' },
  { id: 'en-b1-10', language: 'en', level: 'B1', grammarFocus: '2ª condicional — If + Past + Would: If I were rich, I would travel. (situações imaginárias)' },
  { id: 'en-b1-11', language: 'en', level: 'B1', grammarFocus: 'Modais de dedução no presente — Must (certeza), Might/May (possibilidade), Can\'t (impossibilidade)' },
  { id: 'en-b1-12', language: 'en', level: 'B1', grammarFocus: 'Used to — hábitos e estados do passado: I used to live in Rio. She used to be very shy.' },
  { id: 'en-b1-13', language: 'en', level: 'B1', grammarFocus: 'Pronomes relativos: Who, Which, That — orações relativas restritivas: The man who called... The car that I bought...' },
  { id: 'en-b1-14', language: 'en', level: 'B1', grammarFocus: 'Pronomes relativos: Whose, Where, When — The boy whose dog ran away. The place where we met.' },
  { id: 'en-b1-15', language: 'en', level: 'B1', grammarFocus: 'Orações relativas não-restritivas — My sister, who lives in London, is a doctor. (vírgulas e informação extra)' },
  { id: 'en-b1-16', language: 'en', level: 'B1', grammarFocus: 'Voz passiva no presente simples — is made, are sold, is used, are produced: Coffee is grown in Brazil.' },
  { id: 'en-b1-17', language: 'en', level: 'B1', grammarFocus: 'Voz passiva no passado simples — was built, were written, was invented: The Eiffel Tower was built in 1889.' },
  { id: 'en-b1-18', language: 'en', level: 'B1', grammarFocus: 'So...that e Such...that — causa e efeito: He was so tired that he slept immediately. Such a good film!' },
  { id: 'en-b1-19', language: 'en', level: 'B1', grammarFocus: 'Both, Either, Neither — dois elementos: Both are good. Either day works. Neither option is perfect.' },
  { id: 'en-b1-20', language: 'en', level: 'B1', grammarFocus: 'Causativa: Have/Get + object + past participle — I had my hair cut. She got her car fixed.' },
  { id: 'en-b1-21', language: 'en', level: 'B1', grammarFocus: 'Phrasal verbs com Get — get up, get back, get over, get along (with), get through, get away with' },
  { id: 'en-b1-22', language: 'en', level: 'B1', grammarFocus: 'Phrasal verbs com Take — take off, take up, take out, take back, take on, take over, take after' },
  { id: 'en-b1-23', language: 'en', level: 'B1', grammarFocus: 'Phrasal verbs com Turn — turn on, turn off, turn up, turn down, turn out, turn into, turn around' },
  { id: 'en-b1-24', language: 'en', level: 'B1', grammarFocus: 'Phrasal verbs separáveis vs. inseparáveis — estrutura, posição do objeto e diferenças de sentido' },
  { id: 'en-b1-25', language: 'en', level: 'B1', grammarFocus: 'Idiomas sobre tempo — beat the clock, around the clock, kill time, time flies, in the nick of time' },
  { id: 'en-b1-26', language: 'en', level: 'B1', grammarFocus: 'Idiomas sobre dinheiro — costs an arm and a leg, go broke, save up, be broke, make ends meet' },
  { id: 'en-b1-27', language: 'en', level: 'B1', grammarFocus: 'Idiomas sobre comida e natureza — spill the beans, couch potato, bite the bullet, raining cats and dogs' },
  { id: 'en-b1-28', language: 'en', level: 'B1', grammarFocus: 'Question tags — You\'re Brazilian, aren\'t you? It\'s hot, isn\'t it? She didn\'t call, did she?' },
  { id: 'en-b1-29', language: 'en', level: 'B1', grammarFocus: 'Concordar e discordar naturalmente — I couldn\'t agree more, I doubt it, That\'s a good point, Not necessarily' },
  { id: 'en-b1-30', language: 'en', level: 'B1', grammarFocus: 'Respostas curtas — So do I, Neither do I, I hope so, I think so, I\'m afraid so' },
  { id: 'en-b1-31', language: 'en', level: 'B1', grammarFocus: 'Palavras de ligação de contraste — although, even though, however, whereas, on the other hand, despite' },
  { id: 'en-b1-32', language: 'en', level: 'B1', grammarFocus: 'Palavras de ligação de causa e resultado — therefore, as a result, due to, because of, consequently' },
  { id: 'en-b1-33', language: 'en', level: 'B1', grammarFocus: 'Colocações de viagem e aeroporto — board a flight, check in, catch a connection, go through customs' },
  { id: 'en-b1-34', language: 'en', level: 'B1', grammarFocus: 'Colocações de trabalho — meet a deadline, launch a product, run a meeting, give a presentation' },
  { id: 'en-b1-35', language: 'en', level: 'B1', grammarFocus: 'Frases de esclarecimento — What I mean is..., In other words..., Let me rephrase that..., To clarify...' },
  { id: 'en-b1-36', language: 'en', level: 'B1', grammarFocus: '10 expressões e idiomas essenciais do nível B1' },

  // ── B2: Upper-Intermediate (115–144) ──────────────────────────────────────────
  { id: 'en-b2-01', language: 'en', level: 'B2', grammarFocus: 'Present Perfect Continuous — I\'ve been working all day. She\'s been studying for hours.' },
  { id: 'en-b2-02', language: 'en', level: 'B2', grammarFocus: 'PP Simple vs. Continuous — resultado (I\'ve written the report) vs. duração (I\'ve been writing)' },
  { id: 'en-b2-03', language: 'en', level: 'B2', grammarFocus: 'Past Perfect (Mais-que-perfeito) — I had eaten before she arrived. She had already left.' },
  { id: 'en-b2-04', language: 'en', level: 'B2', grammarFocus: 'Conectar narrativas — Past Simple, Past Continuous e Past Perfect em contexto de história' },
  { id: 'en-b2-05', language: 'en', level: 'B2', grammarFocus: '3ª condicional — If I had known, I would have gone. (arrependimentos e situações impossíveis no passado)' },
  { id: 'en-b2-06', language: 'en', level: 'B2', grammarFocus: 'Desejos no presente — I wish I were taller. I wish I had a car. If only I could speak French.' },
  { id: 'en-b2-07', language: 'en', level: 'B2', grammarFocus: 'Arrependimentos no passado — I wish I had studied harder. If only I had listened to her.' },
  { id: 'en-b2-08', language: 'en', level: 'B2', grammarFocus: 'Discurso indireto: afirmações — He said that he was tired. She told me she would come.' },
  { id: 'en-b2-09', language: 'en', level: 'B2', grammarFocus: 'Discurso indireto: perguntas — She asked me if I was ready. He wanted to know where I lived.' },
  { id: 'en-b2-10', language: 'en', level: 'B2', grammarFocus: 'Discurso indireto: ordens e pedidos — He told me to stop. She asked me not to tell anyone.' },
  { id: 'en-b2-11', language: 'en', level: 'B2', grammarFocus: 'Voz passiva avançada — has been done, will be built, is being studied, was being repaired' },
  { id: 'en-b2-12', language: 'en', level: 'B2', grammarFocus: 'Voz passiva com verbos de relato — It is said that..., It is believed that..., It is reported that...' },
  { id: 'en-b2-13', language: 'en', level: 'B2', grammarFocus: 'Modais de dedução no passado — must have (certeza), might have (possibilidade), can\'t have (impossibilidade)' },
  { id: 'en-b2-14', language: 'en', level: 'B2', grammarFocus: 'Arrependimento e crítica com modais — should have done, ought to have done, needn\'t have done' },
  { id: 'en-b2-15', language: 'en', level: 'B2', grammarFocus: 'Futuro contínuo — I will be working at 8pm tomorrow. She\'ll be travelling next week.' },
  { id: 'en-b2-16', language: 'en', level: 'B2', grammarFocus: 'Futuro perfeito — I will have finished by Friday. By 2030, they will have built the bridge.' },
  { id: 'en-b2-17', language: 'en', level: 'B2', grammarFocus: 'Be used to vs. Get used to — estar acostumado (be used to) vs. acostumar-se (get used to) + noun/-ing' },
  { id: 'en-b2-18', language: 'en', level: 'B2', grammarFocus: 'Adjetivos extremos e modificadores — absolutely exhausted, completely ruined, totally wrong, utterly ridiculous' },
  { id: 'en-b2-19', language: 'en', level: 'B2', grammarFocus: 'Adjetivos participiais — bored/boring, interested/interesting, tired/tiring, excited/exciting' },
  { id: 'en-b2-20', language: 'en', level: 'B2', grammarFocus: 'Even, Even if, Even though, As though — nuances de contraste e comparação' },
  { id: 'en-b2-21', language: 'en', level: 'B2', grammarFocus: 'Expressar probabilidade — bound to, likely to, highly unlikely, there\'s a chance that, odds are' },
  { id: 'en-b2-22', language: 'en', level: 'B2', grammarFocus: 'Colocações fortes com adjetivos — heavy rain, strict rules, strong accent, deep sleep, high risk' },
  { id: 'en-b2-23', language: 'en', level: 'B2', grammarFocus: 'Colocações verbais fortes — firmly believe, warmly welcome, utterly fail, deeply regret, strongly recommend' },
  { id: 'en-b2-24', language: 'en', level: 'B2', grammarFocus: 'Phrasal verbs com Come — come across, come up with, come down with, come back to, come round' },
  { id: 'en-b2-25', language: 'en', level: 'B2', grammarFocus: 'Phrasal verbs com Put — put off, put up with, put away, put forward, put out, put down, put through' },
  { id: 'en-b2-26', language: 'en', level: 'B2', grammarFocus: 'Phrasal verbs com Run — run out of, run into, run over, run for, run away, run through, run up' },
  { id: 'en-b2-27', language: 'en', level: 'B2', grammarFocus: 'Inglês falado: elisão e assimilação — wanna, gonna, gimme, kinda, dunno, gotta, hafta' },
  { id: 'en-b2-28', language: 'en', level: 'B2', grammarFocus: 'Inglês informal: omissão de palavras em contextos casuais — Seen John? Coming tonight? Sounds good.' },
  { id: 'en-b2-29', language: 'en', level: 'B2', grammarFocus: 'Inglês britânico vs. americano — lift/elevator, flat/apartment, colour/color, biscuit/cookie, queue/line' },
  { id: 'en-b2-30', language: 'en', level: 'B2', grammarFocus: '10 expressões e idiomas essenciais do nível B2' },

  // ── C1: Advanced (145–160) ────────────────────────────────────────────────────
  { id: 'en-c1-01', language: 'en', level: 'C1', grammarFocus: 'Inversão com advérbios negativos — Never have I..., Hardly had I..., Not only did she..., Rarely do we...' },
  { id: 'en-c1-02', language: 'en', level: 'C1', grammarFocus: 'Frases clivadas para ênfase — It was John who called. What I need is support. All I want is peace.' },
  { id: 'en-c1-03', language: 'en', level: 'C1', grammarFocus: 'Orações participiais de razão — Not knowing what to do, she called for help. Feeling exhausted...' },
  { id: 'en-c1-04', language: 'en', level: 'C1', grammarFocus: 'Orações participiais de tempo — Having finished my work, I went home. Having been told the news...' },
  { id: 'en-c1-05', language: 'en', level: 'C1', grammarFocus: 'Condicionais mistas — passado afetando o presente: If I had studied, I would be a doctor now.' },
  { id: 'en-c1-06', language: 'en', level: 'C1', grammarFocus: 'Subjuntivo em inglês — I demand that he apologize. It\'s vital that she be there. If I were you...' },
  { id: 'en-c1-07', language: 'en', level: 'C1', grammarFocus: 'Marcadores de discurso avançados em inglês falado — by the way, as a matter of fact, to be honest, come to think of it' },
  { id: 'en-c1-08', language: 'en', level: 'C1', grammarFocus: 'Hedging — suavizar a fala: It seems that, arguably, presumably, to some extent, it could be argued that' },
  { id: 'en-c1-09', language: 'en', level: 'C1', grammarFocus: 'Substantivos e adjetivos de phrasal verbs — a breakthrough, a letdown, a takeaway, worn-out, built-up' },
  { id: 'en-c1-10', language: 'en', level: 'C1', grammarFocus: 'Comparativos duplos — The more you study, the better you get. The harder I work, the luckier I seem.' },
  { id: 'en-c1-11', language: 'en', level: 'C1', grammarFocus: 'Phrasal verbs para negócios e negociação — draw up, back down, fall through, push for, iron out, wrap up' },
  { id: 'en-c1-12', language: 'en', level: 'C1', grammarFocus: 'Phrasal verbs com múltiplos significados — set up, work out, make out, bring up, carry out, take in' },
  { id: 'en-c1-13', language: 'en', level: 'C1', grammarFocus: 'Palavras de ligação avançadas — nevertheless, furthermore, conversely, albeit, notwithstanding, henceforth' },
  { id: 'en-c1-14', language: 'en', level: 'C1', grammarFocus: 'Colocações avançadas com preposições — comply with, derive from, devoid of, conducive to, consistent with' },
  { id: 'en-c1-15', language: 'en', level: 'C1', grammarFocus: 'Idiomas para situações difíceis — bite the bullet, face the music, weather the storm, take the heat' },
  { id: 'en-c1-16', language: 'en', level: 'C1', grammarFocus: '10 expressões e idiomas essenciais do nível C1' },

  // ── C2: Mastery (161–172) ─────────────────────────────────────────────────────
  { id: 'en-c2-01', language: 'en', level: 'C2', grammarFocus: 'Verbos latinizados vs. phrasal verbs — formal vs. informal: commence/start, endeavour/try, terminate/end' },
  { id: 'en-c2-02', language: 'en', level: 'C2', grammarFocus: 'Pares binomiais — sick and tired, loud and clear, by and large, safe and sound, pros and cons' },
  { id: 'en-c2-03', language: 'en', level: 'C2', grammarFocus: 'Nuances dos modais — may well, might as well, dare, need, had better, be supposed to, be bound to' },
  { id: 'en-c2-04', language: 'en', level: 'C2', grammarFocus: 'Flexibilidade sintática e variedade de frases — inversão, ênfase, elipse e outras estruturas estilísticas' },
  { id: 'en-c2-05', language: 'en', level: 'C2', grammarFocus: 'Implicatura conversacional — ler nas entrelinhas: what is said vs. what is meant em inglês' },
  { id: 'en-c2-06', language: 'en', level: 'C2', grammarFocus: 'Dominar sarcasmo e understatement em inglês — That was quite an experience. (ironia britânica)' },
  { id: 'en-c2-07', language: 'en', level: 'C2', grammarFocus: 'Variações regionais — diferenças entre inglês americano, britânico e australiano (vocabulário e pronúncia)' },
  { id: 'en-c2-08', language: 'en', level: 'C2', grammarFocus: 'Gírias e coloquialismos contemporâneos — lit, vibe, ghosting, flex, slay, lowkey, no cap, woke' },
  { id: 'en-c2-09', language: 'en', level: 'C2', grammarFocus: 'Idiomas avançados de sucesso e fracasso — go through the roof, fall flat, hit the nail on the head, miss the mark' },
  { id: 'en-c2-10', language: 'en', level: 'C2', grammarFocus: 'A linguagem da persuasão, retórica e oratória — estruturas argumentativas e recursos retóricos' },
  { id: 'en-c2-11', language: 'en', level: 'C2', grammarFocus: 'Fluência total — conectar ideias naturalmente sem traduzir do português: pensamento direto em inglês' },
  { id: 'en-c2-12', language: 'en', level: 'C2', grammarFocus: '10 expressões e idiomas essenciais do nível C2' },
];

// ─── Lesson selection ─────────────────────────────────────────────────────────

const LESSON_MAP: Record<SupportedLanguage, LessonDefinition[]> = {
  fr: FRENCH_LESSONS,
  en: ENGLISH_LESSONS,
};

/** All lessons for a given language, in curriculum order. */
export function getLessonsForLanguage(language: SupportedLanguage): LessonDefinition[] {
  return LESSON_MAP[language];
}

/**
 * Returns the lesson the user should study next.
 * `currentLessonId` is the ID stored in `profile.lessonProgress[language]`.
 * Falls back to the first lesson if no progress is recorded.
 */
export function getNextLesson(language: SupportedLanguage, currentLessonId?: string): LessonDefinition {
  const lessons = LESSON_MAP[language];
  if (!currentLessonId) return lessons[0];
  const lesson = lessons.find((l) => l.id === currentLessonId);
  return lesson ?? lessons[0];
}

/**
 * Returns the ID of the lesson that comes after `completedLessonId`.
 * Returns null if the completed lesson is the last one in the curriculum.
 */
export function getNextLessonId(language: SupportedLanguage, completedLessonId: string): string | null {
  const lessons = LESSON_MAP[language];
  const idx = lessons.findIndex((l) => l.id === completedLessonId);
  if (idx === -1 || idx >= lessons.length - 1) return null;
  return lessons[idx + 1].id;
}

export function getLessonById(id: string): LessonDefinition | undefined {
  return [...FRENCH_LESSONS, ...ENGLISH_LESSONS].find((l) => l.id === id);
}
