import type { ErrorCorrectionData } from '@/types';

/** Values generated by the AI (or legacy data) meaning "remove the error word". */
const DELETION_MARKERS = new Set([
  '',
  '---',
  '—',
  '–',
  '-',
  'nada',
  '(nada)',
  'apagar',
  '(apagar)',
  'remover',
  '(remover)',
  'delete',
  'DELETE',
  '∅',
]);

const DELETION_ANSWER_MARKERS = new Set([
  '',
  'nada',
  'apagar',
  'remover',
  'delete',
  '---',
  '—',
  '–',
  '-',
  '∅',
  '(nada)',
  '(apagar)',
  '(remover)',
]);

export function isDeletionCorrection(correctWord: string | undefined | null): boolean {
  if (correctWord == null) return false;
  return DELETION_MARKERS.has(correctWord.trim().toLowerCase());
}

export function isDeletionAnswer(input: string): boolean {
  return DELETION_ANSWER_MARKERS.has(input.trim().toLowerCase());
}

export function formatErrorCorrectionAnswer(data: ErrorCorrectionData): string {
  if (isDeletionCorrection(data.correct_word)) {
    return `Apague "${data.error_word}" (deixe em branco)`;
  }
  return data.correct_word;
}

export function errorCorrectionPlaceholder(data: ErrorCorrectionData): string {
  if (isDeletionCorrection(data.correct_word)) {
    return `Apague "${data.error_word}" — deixe em branco`;
  }
  return `Substitua "${data.error_word}"…`;
}
